In [ ]:
import pandas as pd
import numpy as np

In [ ]:
person_entities_df = pd.read_csv("books_person_entities.csv")

In [ ]:
person_entities_df.tail(15)

,book,sentence,person_entities
45128,Book 3,NaN,NaN
45129,Book 3,"""Indeed,"" Leto said.",Leto
45130,Book 3,"He lifted himself from the throne, a curiously...",NaN
45131,Book 3,"Leto stepped down then to Ghanima's level, mov...","Leto, Ghanima"
45132,Book 3,"""Note this, cousin Harq al-Ada.",Harq al-Ada
45133,Book 3,This is the way it will always be with us.,NaN
45134,Book 3,We'll stand thus when we are married.,NaN
45135,Book 3,"Back to back, each looking outward from the ot...",NaN
45136,Book 3,"He turned, looked mockingly at Farad'n, lowere...","Farad'n, Ghanima"
45137,Book 3,Remember that when you whisper of love and sof...,NaN
45138,Book 3,"Your back will remain exposed.""",NaN
45139,Book 3,"Turning from them, he strode down the steps in...",NaN
45140,Book 3,NaN,NaN
45141,Book 3,"Ghanima once more took Farad'n's hand, but her...","Ghanima, Farad'n, Leto"
45142,Book 3,"""One of us had to accept the agony,"" she said,...",NaN

In [ ]:
# Filter rows with at least two names in the 'person_entities' column
filtered_df = person_entities_df[
    person_entities_df["person_entities"].apply(
        lambda x: isinstance(x, str) and len(x.split(", ")) >= 2
    )
]

# Display filtered rows
print(f"Filtered rows: {len(filtered_df)}")
print(filtered_df.head())

Filtered rows: 2431
       book                                           sentence  \
15   Book 1  Paul's mother answered in her soft contralto: ...
45   Book 1  Now the Harkonnens were leaving to be replaced...
46   Book 1  Yet, Hawat had said, this appearance contained...
133  Book 1  Jessica's hand went to Paul's shoulder, tighte...
140  Book 1  The old woman studied Paul in one gestalten fl...

         person_entities
15        Paul, Atreides
45      Harkonnens, Leto
46           Hawat, Leto
133        Jessica, Paul
140  Paul, Jessica, Duke

In [ ]:
filtered_df.sample(10)

,book,sentence,person_entities
17845,Book 1,A sighing whisper of awe passed through the cr...,"Jessica, A Bene Gesserit"
17567,Book 1,"Your first thought was to protect Chani.""\n ...","Chani, Stilgar"
5228,Book 1,"""Almost exactly, my Lord,"" Kynes said, and he ...","Kynes, Sire, Halleck"
34888,Book 3,She still retained the haughtiness she'd learn...,"Shaddam IV, Alia"
24271,Book 2,"""Listen to the great Stilgar!"" Alia said, keep...","Stilgar, Alia"
4558,Book 1,"""We are indebted to you, Dr. Kynes,"" Leto said.","Kynes, Leto"
27221,Book 2,"""Did you inquire of Lichna?"" Otheym asked sudd...","Lichna, Otheym, Dhuri"
12692,Book 1,"""Perhaps if I explain to Jamis how--"" \n ""E...","Jamis, Jamis"
21335,Book 1,SANDCRAWLER: general term for machinery design...,"SANDCRAWLER, SANDMASTER"
35888,Book 3,"But Jessica raged on: ""This Ghadhean al-Fali, ...","Jessica, This Ghadhean al-Fali"

In [ ]:
indexes_to_drop = [20853]
filtered_df = filtered_df.drop(index=indexes_to_drop)

In [ ]:
filtered_df.shape

(2430, 3)

In [ ]:
#change names
mapping_data = [
    {"Alias": "-Leto", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "-Leto Atreides II", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "-Leto II", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "-Liet-Kynes", "Person": "Liet-Kynes", "House": "Atreides"},
    {"Alias": "-Muad'Dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "-Palimbasha", "Person": "Palimbasha", "House": "Fremen"},
    {"Alias": "-Pardot Kynes", "Person": "Pardot Kynes", "House": "Fremen"},
    {"Alias": "-Stilgar", "Person": "Stilgar", "House": "Atreides"},
    {"Alias": "-Tagir Mohandis", "Person": "Tagir Mohandis", "House": "Bene Gesserit"},
    {"Alias": "-The Preacher at Arrakeen", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Abedi Jalal", "Person": "Abedi Jalal", "House": "Fremen"},
    {"Alias": "Abu Dhur", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Abu d' Dhur", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Abulurd", "Person": "Abulurd", "House": "Harkonnen"},
    {"Alias": "Abumojandis", "Person": "Abumojandis", "House": "Fremen"},
    {"Alias": "Accursed One", "Person": "Alia", "House": "Atreides"},
    {"Alias": "After Harq al-Ada", "Person": "Farad'n", "House": "Corrino"},
    {"Alias": "Agarves", "Person": "Buer Agarves", "House": "Fremen"},
    {"Alias": "Aiya", "Person": "Alia", "House": "Atreides"},
    {"Alias": "Al-Fali", "Person": "Ghadhean al-Fali", "House": "Fremen"},
    {"Alias": "Al-Fali's", "Person": "Ghadhean al-Fali", "House": "Fremen"},
    {"Alias": "Albe", "Person": "Albe", "House": "Atreides"},
    {"Alias": "Alia", "Person": "Alia", "House": "Atreides"},
    {"Alias": "Alia Atreides", "Person": "Alia", "House": "Atreides"},
    {"Alias": "Alia of the Knife", "Person": "Alia", "House": "Atreides"},
    {"Alias": "Alia-of-the-Knife", "Person": "Alia", "House": "Atreides"},
    {"Alias": "Alia-the-Strange-One", "Person": "Alia", "House": "Atreides"},
    {"Alias": "Anirul", "Person": "Anirul", "House": "Corrino"},
    {"Alias": "Aramsham", "Person": "Aramsham", "House": "Corrino"},
    {"Alias": "Arkie", "Person": "Arkie", "House": "Atreides"},
    {"Alias": "Aryeh", "Person": "Alia", "House": "Atreides"},
    {"Alias": "Assan", "Person": "Assan", "House": "Atreides"},
    {"Alias": "Assan Tariq", "Person": "Assan", "House": "Atreides"},
    {"Alias": "Assan Tariq's", "Person": "Assan", "House": "Atreides"},
    {"Alias": "Auliya", "Person": "Alia", "House": "Atreides"},
    {"Alias": "Bannerjee", "Person": "Bannerjee", "House": "Atreides"},
    {"Alias": "Bar", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "Baron", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "Batigh", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "Beast Rabban", "Person": "Glossu", "House": "Harkonnen"},
    {"Alias": "Behaleth", "Person": "Behaleth", "House": "Fremen"},
    {"Alias": "Bewt", "Person": "Lingar Bewt", "House": "Arrakis Water seller"},
    {"Alias": "Bijaz", "Person": "Bijaz", "House": "Atreides"},
    {"Alias": "Bikouros", "Person": "Bikouros", "House": "Fremen"},
    {"Alias": "Bomoko", "Person": "Toure Bomoko", "House": "CET"},
    {"Alias": "Bronso", "Person": "Bronso", "House": "Ixian"},
    {"Alias": "Buer", "Person": "Buer", "House": "Fremen"},
    {"Alias": "Buer Agarves", "Person": "Buer", "House": "Fremen"},
    {"Alias": "Cahueit", "Person": "Cahueit", "House": "Fremen"},
    {"Alias": "Chalice", "Person": "Chalice", "House": "Corrino"},
    {"Alias": "Chani", "Person": "Chani", "House": "Fremen"},
    {"Alias": "Chatt", "Person": "Chatt", "House": "Fremen"},
    {"Alias": "Choda", "Person": "Choda", "House": "Atreides"},
    {"Alias": "Coan", "Person": "Alia", "House": "Atreides"},
    {"Alias": "Coss", "Person": "Coss", "House": "Atreides"},
    {"Alias": "Czigo", "Person": "Czigo", "House": "Harkonnen"},
    {"Alias": "Dalak", "Person": "Dalak Fenring", "House": "Corrino"},
    {"Alias": "Dhuri", "Person": "Dhuri", "House": "Fremen"},
    {"Alias": "Djedida", "Person": "Djedida", "House": "Fremen"},
    {"Alias": "Doc", "Person": "Yueh", "House": "Atreides"},
    {"Alias": "Drisq", "Person": "Drisq", "House": "Atreides"},
    {"Alias": "Duke", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "Duncan", "Person": "Duncan", "House": "Atreides"},
    {"Alias": "Duncan Idaho", "Person": "Duncan", "House": "Atreides"},
    {"Alias": "Edric", "Person": "Edric", "House": "Corrino"},
    {"Alias": "Elpa", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Elrood IX", "Person": "Elrood IX", "House": "Corrino"},
    {"Alias": "Esmar", "Person": "Esmar", "House": "Atreides"},
    {"Alias": "Esmar Tuek", "Person": "Esmar", "House": "Atreides"},
    {"Alias": "Essas Paymon", "Person": "Essas Paymon", "House": "Nebiro"},
    {"Alias": "Farad'n", "Person": "Farad'n", "House": "Corrino"},
    {"Alias": "Farok", "Person": "Farok", "House": "Fremen"},
    {"Alias": "Farrukh", "Person": "Farrukh", "House": "Fremen"},
    {"Alias": "Fenring", "Person": "Hasimir", "House": "Corrino"},
    {"Alias": "Feyd", "Person": "Feyd-Rautha", "House": "Harkonnen"},
    {"Alias": "Feyd-Rautha", "Person": "Feyd-Rautha", "House": "Harkonnen"},
    {"Alias": "Feyd-Rautha Harkonnen", "Person": "Feyd-Rautha", "House": "Harkonnen"},
    {"Alias": "Feyd-Rautha Rabban", "Person": "Feyd-Rautha", "House": "Harkonnen"},
    {"Alias": "Feyd-Rautha's", "Person": "Feyd-Rautha", "House": "Harkonnen"},
    {"Alias": "Fremen Mahdi", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Gaib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Gains Helen Mohiam", "Person": "Helen Mohaim", "House": "Bene Gesserit"},
    {"Alias": "Gaius Helen", "Person": "Helen Mohaim", "House": "Bene Gesserit"},
    {"Alias": "Gaius Helen Mohiam", "Person": "Helen Mohaim", "House": "Bene Gesserit"},
    {"Alias": "Gaius Helen Mohiam's", "Person": "Helen Mohaim", "House": "Bene Gesserit"},
    {"Alias": "Geoff", "Person": "Geoff", "House": "Fremen"},
    {"Alias": "Georad", "Person": "Georad", "House": "Unknown"},
    {"Alias": "Ghadhean", "Person": "Ghadhean", "House": "Fremen"},
    {"Alias": "Ghadhean al-Fali", "Person": "Ghadhean", "House": "Fremen"},
    {"Alias": "Ghani", "Person": "Ghani", "House": "Atreides"},
    {"Alias": "Ghanima", "Person": "Ghani", "House": "Atreides"},
    {"Alias": "Glossu Rabban", "Person": "Glossu", "House": "Harkonnen"},
    {"Alias": "Gurney", "Person": "Gurney", "House": "Atreides"},
    {"Alias": "Gurney Halleck", "Person": "Gurney", "House": "Atreides"},
    {"Alias": "Gurney Halleck's", "Person": "Gurney", "House": "Atreides"},
    {"Alias": "Gurney Halleck.", "Person": "Gurney", "House": "Atreides"},
    {"Alias": "Haderach", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Halleck", "Person": "Gurney", "House": "Atreides"},
    {"Alias": "Har", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "Harah", "Person": "Harah", "House": "Fremen"},
    {"Alias": "Harkon", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "Harkon--", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "Harkonnen", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "Harq al-Ada", "Person": "Farad'n", "House": "Corrino"},
    {"Alias": "Farad'n", "Person": "Farad'n", "House": "Corrino"},
    {"Alias": "Harrah", "Person": "Harah", "House": "Fremen"},
    {"Alias": "Hasimir Fenring", "Person": "Hasimir", "House": "Fenring"},
    {"Alias": "Hawat", "Person": "Hawat", "House": "Atreides"},
    {"Alias": "Hawk", "Person": "Hawat", "House": "Atreides"},
    {"Alias": "Hawt", "Person": "Hawat", "House": "Atreides"},
    {"Alias": "Hobars", "Person": "Hobars", "House": "Fremen"},
    {"Alias": "Holtzman", "Person": "Holtzman", "House": "Unknown"},
    {"Alias": "Iakin Nefud", "Person": "Iakin", "House": "Harkonnen"},
    {"Alias": "Idaho", "Person": "Duncan", "House": "Atreides"},
    {"Alias": "Irulan", "Person": "Irulan", "House": "Corrino"},
    {"Alias": "JESSICA", "Person": "Jessica", "House": "Atreides"},
    {"Alias": "JESSICA--", "Person": "Jessica", "House": "Atreides"},
    {"Alias": "Jamis", "Person": "Jamis", "House": "Fremen"},
    {"Alias": "Jamis'll", "Person": "Jamis", "House": "Fremen"},
    {"Alias": "Javid", "Person": "Javid", "House": "Fremen"},
    {"Alias": "Jessica", "Person": "Jessica", "House": "Fremen"},
    {"Alias": "Josifa", "Person": "Josifa", "House": "Corrino"},
    {"Alias": "KWISATZ HADERACH", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Kaleff", "Person": "Kaleff", "House": "Fremen"},
    {"Alias": "Keke the Lame", "Person": "Keke", "House": "Fremen"},
    {"Alias": "Kinet", "Person": "Kinet", "House": "Harkonnen"},
    {"Alias": "Korba", "Person": "Korba", "House": "Fremen"},
    {"Alias": "Kwisatz Haderach", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Kynes", "Person": "Liet-Kynes", "House": "Fremen"},
    {"Alias": "LADY ALIA ATREIDES", "Person": "Alia", "House": "Atreides"},
    {"Alias": "LETO ATREIDES", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "LISAN AL-GAIB", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Larus", "Person": "Larus", "House": "Fremen"},
    {"Alias": "Leaper", "Person": "Chatt", "House": "Fremen"},
    {"Alias": "Legg", "Person": "Legg", "House": "Fremen"},
    {"Alias": "Lemil", "Person": "Lemil", "House": "Atreides"},
    {"Alias": "Leto", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "Leto Atreides", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "Leto Atreides I", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "Leto Atreides II", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "Leto I", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "Leto II", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "Leto-Atreides", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "Leto-Batigh", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "Lichna", "Person": "Lichna", "House": "Unknown"},
    {"Alias": "Liet", "Person": "Liet-Kynes", "House": "Fremen"},
    {"Alias": "Liet-Kynes", "Person": "Liet-Kynes", "House": "Fremen"},
    {"Alias": "Lingar Bewt", "Person": "Lingar Bewt", "House": "Arrakis Water seller"},
    {"Alias": "Lisan al-", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Lisan al-Gaib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Lu", "Person": "Lu", "House": "Unknown"},
    {"Alias": "Lu Tung-pin", "Person": "Lu", "House": "Unknown"},
    {"Alias": "MAHDI", "Person": "Paul", "House": "Atreides"},
    {"Alias": "MARGOT LADY FENRING\"", "Person": "Margot Fenring", "House": "Fenring"},
    {"Alias": "MF", "Person": "Margot Fenring", "House": "Fenring"},
    {"Alias": "MUDIR NAHYA", "Person": "Glossu", "House": "Harkonnen"},
    {"Alias": "Mahdi", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Mahdinate", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Maometh", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Mapes", "Person": "Mapes", "House": "Atreides"},
    {"Alias": "Margot", "Person": "Margot Fenring", "House": "Fenring"},
    {"Alias": "Mattai", "Person": "Mattai", "House": "Atreides"},
    {"Alias": "Maya", "Person": "Maya", "House": "Bene Gesserit"},
    {"Alias": "Melides", "Person": "Melides", "House": "Atreides"},
    {"Alias": "Messiah", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "Mirzabah", "Person": "Mirzabah", "House": "Fremen"},
    {"Alias": "Mitha", "Person": "Mitha", "House": "Fremen"},
    {"Alias": "Mohandis", "Person": "Mohandis", "House": "Atreides"},
    {"Alias": "Mohiam", "Person": "Helen Mohaim", "House": "Bene Gesserit"},
    {"Alias": "Molitor", "Person": "Piter", "House": "Atreides"},
    {"Alias": "Mother", "Person": "Jessica", "House": "Atreides"},
    {"Alias": "Mua-a-a-ad'Dib!\"", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'Dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'Dib!", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'Dib's", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'Dib.", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'Dib/Paul Atreides", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Mujahid Shafqat", "Person": "Mujahid Shafqat", "House": "Fremen"},
    {"Alias": "Muriz", "Person": "Muriz", "House": "Fremen"},
    {"Alias": "My Duke!", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "My Lady?", "Person": "Jessica", "House": "Atreides"},
    {"Alias": "Naib", "Person": "Naib", "House": "Fremen"},
    {"Alias": "Naibs", "Person": "Naib", "House": "Fremen"},
    {"Alias": "Namri", "Person": "Namri", "House": "Bene Gesserit"},
    {"Alias": "Nefud", "Person": "Nefud", "House": "Harkonnen"},
    {"Alias": "Neshou", "Person": "Neshou", "House": "Fremen"},
    {"Alias": "Nisai", "Person": "Nisai", "House": "Fremen"},
    {"Alias": "Ohashi", "Person": "Ohashi", "House": "Fremen"},
    {"Alias": "Orlop", "Person": "Orlop", "House": "Fremen"},
    {"Alias": "Otheym", "Person": "Otheym", "House": "Fremen"},
    {"Alias": "Our Lady of Dune", "Person": "Jessica", "House": "Atreides"},
    {"Alias": "Padishah", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "Padishah Emperor", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "Palimbasha", "Person": "Palimbasha", "House": "Fremen"},
    {"Alias": "Panegyrist", "Person": "Korba", "House": "Fremen"},
    {"Alias": "Pardee", "Person": "Pardee", "House": "Harkonnen"},
    {"Alias": "Pardot Kynes", "Person": "Pardot Kynes", "House": "Fremen"},
    {"Alias": "Paul", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Atreides", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Emperor", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Jessica", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Muad'Dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Muad'Dib.", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Muad'dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Muad'dib.", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul-Muad'Dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul-Muad'Dib's", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul-Muad'dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Leto Atreides", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "Leto Atreides I", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "Leto Atreides II", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "Leto I", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "Leto II", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "Leto-Atreides", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "Leto-Batigh", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "Lichna", "Person": "Lichna", "House": "Unknown"},
    {"Alias": "Liet", "Person": "Liet-Kynes", "House": "Fremen"},
    {"Alias": "Liet-Kynes", "Person": "Liet-Kynes", "House": "Fremen"},
    {"Alias": "Lingar Bewt", "Person": "Lingar Bewt", "House": "Arrakis Water seller"},
    {"Alias": "Lisan al-", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Lisan al-Gaib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Lu", "Person": "Lu", "House": "Unknown"},
    {"Alias": "Lu Tung-pin", "Person": "Lu", "House": "Unknown"},
    {"Alias": "MAHDI", "Person": "Paul", "House": "Atreides"},
    {"Alias": "MARGOT LADY FENRING\"", "Person": "Margot Fenring", "House": "Fenring"},
    {"Alias": "MF", "Person": "Margot Fenring", "House": "Fenring"},
    {"Alias": "MUDIR NAHYA", "Person": "Glossu", "House": "Harkonnen"},
    {"Alias": "Mahdi", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Mahdinate", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Maometh", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Mapes", "Person": "Mapes", "House": "Atreides"},
    {"Alias": "Margot", "Person": "Margot Fenring", "House": "Fenring"},
    {"Alias": "Mattai", "Person": "Mattai", "House": "Atreides"},
    {"Alias": "Maya", "Person": "Maya", "House": "Bene Gesserit"},
    {"Alias": "Melides", "Person": "Melides", "House": "Atreides"},
    {"Alias": "Messiah", "Person": "Leto II", "House": "Atreides"},
    {"Alias": "Mirzabah", "Person": "Mirzabah", "House": "Fremen"},
    {"Alias": "Mitha", "Person": "Mitha", "House": "Fremen"},
    {"Alias": "Mohandis", "Person": "Mohandis", "House": "Atreides"},
    {"Alias": "Mohiam", "Person": "Helen Mohaim", "House": "Bene Gesserit"},
    {"Alias": "Molitor", "Person": "Piter", "House": "Atreides"},
    {"Alias": "Mother", "Person": "Jessica", "House": "Atreides"},
    {"Alias": "Mua-a-a-ad'Dib!\"", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'Dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'Dib!", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'Dib's", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'Dib.", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'Dib/Paul Atreides", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Muad'dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Mujahid Shafqat", "Person": "Mujahid Shafqat", "House": "Fremen"},
    {"Alias": "Muriz", "Person": "Muriz", "House": "Fremen"},
    {"Alias": "My Duke!", "Person": "Leto I", "House": "Atreides"},
    {"Alias": "My Lady?", "Person": "Jessica", "House": "Atreides"},
    {"Alias": "Naib", "Person": "Naib", "House": "Fremen"},
    {"Alias": "Naibs", "Person": "Naib", "House": "Fremen"},
    {"Alias": "Namri", "Person": "Namri", "House": "Bene Gesserit"},
    {"Alias": "Nefud", "Person": "Nefud", "House": "Harkonnen"},
    {"Alias": "Neshou", "Person": "Neshou", "House": "Fremen"},
    {"Alias": "Nisai", "Person": "Nisai", "House": "Fremen"},
    {"Alias": "Ohashi", "Person": "Ohashi", "House": "Fremen"},
    {"Alias": "Orlop", "Person": "Orlop", "House": "Fremen"},
    {"Alias": "Otheym", "Person": "Otheym", "House": "Fremen"},
    {"Alias": "Our Lady of Dune", "Person": "Jessica", "House": "Atreides"},
    {"Alias": "Padishah", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "Padishah Emperor", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "Palimbasha", "Person": "Palimbasha", "House": "Fremen"},
    {"Alias": "Panegyrist", "Person": "Korba", "House": "Fremen"},
    {"Alias": "Pardee", "Person": "Pardee", "House": "Harkonnen"},
    {"Alias": "Pardot Kynes", "Person": "Pardot Kynes", "House": "Fremen"},
    {"Alias": "Paul", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Atreides", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Emperor", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Jessica", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Muad'Dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Muad'Dib.", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Muad'dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul Muad'dib.", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul-Muad'Dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul-Muad'Dib's", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Paul-Muad'dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Pay", "Person": "Essas Paymon", "House": "Nebiro"},
    {"Alias": "Paymon", "Person": "Essas Paymon", "House": "Nebiro"},
    {"Alias": "Piter", "Person": "Piter", "House": "Atreides"},
    {"Alias": "Piter de Vries", "Person": "Piter", "House": "Atreides"},
    {"Alias": "Preacher", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Prophet", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Rabban", "Person": "Glossu", "House": "Harkonnen"},
    {"Alias": "Rabban Harkonnen", "Person": "Glossu", "House": "Harkonnen"},
    {"Alias": "Rajia", "Person": "Rajia", "House": "Fremen"},
    {"Alias": "Ramallo", "Person": "Ramallo", "House": "Fremen"},
    {"Alias": "Rasir", "Person": "Rasir", "House": "Fremen"},
    {"Alias": "Rautha", "Person": "Feyd-Rautha", "House": "Harkonnen"},
    {"Alias": "Rugi", "Person": "Rugi", "House": "Corrino"},
    {"Alias": "Ruinous Irulan", "Person": "Irulan", "House": "Corrino"},
    {"Alias": "Saajid", "Person": "Saajid", "House": "Fremen"},
    {"Alias": "Sabiha", "Person": "Sabiha", "House": "Fremen"},
    {"Alias": "Sayyadina Chani", "Person": "Chani", "House": "Fremen"},
    {"Alias": "Sayyadina Jessica", "Person": "Jessica", "House": "Atreides"},
    {"Alias": "Scarface", "Person": "Kinet", "House": "Harkonnen"},
    {"Alias": "Scribe", "Person": "Farad'n", "House": "Corrino"},
    {"Alias": "Scytale", "Person": "Scytale", "House": "Bene Gesserit"},
    {"Alias": "Shaddam", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "Shaddam I.", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "Shaddam IV", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "Shaddam IV's", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "Shakkad the Wise", "Person": "Shakkad", "House": "Fremen"},
    {"Alias": "Shamir", "Person": "Shamir", "House": "Unknown"},
    {"Alias": "Sheba", "Person": "Sheba", "House": "Bene Gesserit"},
    {"Alias": "Shimoom", "Person": "Shimoom", "House": "Fremen"},
    {"Alias": "Shishakli", "Person": "Shishakli", "House": "Fremen"},
    {"Alias": "Shoab", "Person": "Shoab", "House": "Fremen"},
    {"Alias": "Sihaya", "Person": "Chani", "House": "Fremen"},
    {"Alias": "Soo-Soo", "Person": "Soo-Soo", "House": "Harkonnen"},
    {"Alias": "Soo-Soo Sook", "Person": "Soo-Soo", "House": "Harkonnen"},
    {"Alias": "Soo-soo-Sook", "Person": "Soo-Soo", "House": "Harkonnen"},
    {"Alias": "St. Alia", "Person": "Alia", "House": "Atreides"},
    {"Alias": "Staban Tuek", "Person": "Staban", "House": "Harkonnen"},
    {"Alias": "Stil", "Person": "Stilgar", "House": "Atreides"},
    {"Alias": "Stil--", "Person": "Stilgar", "House": "Atreides"},
    {"Alias": "Stilgar", "Person": "Stilgar", "House": "Atreides"},
    {"Alias": "Stiliar", "Person": "Stilgar", "House": "Atreides"},
    {"Alias": "Subiay", "Person": "Subiay", "House": "Fremen"},
    {"Alias": "Tabrite Buer Agarves", "Person": "Buer", "House": "Fremen"},
    {"Alias": "Tagir Mohandis", "Person": "Tagir Mohandis", "House": "Fremen"},
    {"Alias": "Tandis", "Person": "Tandis", "House": "Fremen"},
    {"Alias": "Tariq", "Person": "Assan", "House": "Atreides"},
    {"Alias": "Tasmin", "Person": "Tasmin", "House": "Unknown"},
    {"Alias": "Tasmin Sink", "Person": "Tasmin", "House": "Unknown"},
    {"Alias": "Tecrube", "Person": "Tecrube", "House": "Fremen"},
    {"Alias": "Tharthar", "Person": "Tharthar", "House": "Atreides"},
    {"Alias": "The Count Rabban", "Person": "Glossu", "House": "Harkonnes"},
    {"Alias": "The Emperor", "Person": "Paul", "House": "Atreides"},
    {"Alias": "The Emperor Paul Muad'dib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "The Guest of the Cavern", "Person": "Lu", "House": "Unknown"},
    {"Alias": "The Lisan al-Gaib", "Person": "Paul", "House": "Atreides"},
    {"Alias": "The Mother of Chaos", "Person": "Helen Mohaim", "House": "Bene Gesserit"},
    {"Alias": "The Old Baron", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "The Padishah Emperor", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "The Preacher", "Person": "Paul", "House": "Atreides"},
    {"Alias": "The Preacher's", "Person": "Paul", "House": "Atreides"},
    {"Alias": "The Princess Irulan", "Person": "Irulan", "House": "Corrino"},
    {"Alias": "The Shadout Mapes", "Person": "Mapes", "House": "Atreides"},
    {"Alias": "The Siridar-Baron", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "The Umma Regent", "Person": "Paul", "House": "Atreides"},
    {"Alias": "This Ghadhean al-Fali", "Person": "Ghadhean", "House": "Fremen"},
    {"Alias": "Thufir", "Person": "Hawat", "House": "Atreides"},
    {"Alias": "Thufir Hawat", "Person": "Hawat", "House": "Atreides"},
    {"Alias": "Tibana", "Person": "Tibana", "House": "Unknown"},
    {"Alias": "Toure Bomoko", "Person": "Toure Bomoko", "House": "CET"},
    {"Alias": "Truthsayer", "Person": "Helen Mohaim", "House": "Bene Gesserit"},
    {"Alias": "Tuck", "Person": "Tuek's Sietch", "House": "Arrakis Water seller"},
    {"Alias": "Tuek", "Person": "Tuek's Sietch", "House": "Arrakis Water seller"},
    {"Alias": "Turok", "Person": "Turok", "House": "Fremen"},
    {"Alias": "Tyek", "Person": "Tuek's Sietch", "House": "Arrakis Water seller"},
    {"Alias": "Tyekanik", "Person": "Tuek's Sietch", "House": "Arrakis Water seller"},
    {"Alias": "UMMA", "Person": "Paul", "House": "Atreides"},
    {"Alias": "USUL", "Person": "Paul", "House": "Atreides"},
    {"Alias": "Umman Kudu", "Person": "Umman", "House": "Harkonnen"},
    {"Alias": "Usul", "Person": "Paul", "House": "Atreides"},
    {"Alias": "VLADIMIR HARKONNEN", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "Vladimir", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "Vladimir Harkonnen", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "Wanna", "Person": "Wanna", "House": "Bene Gesserit"},
    {"Alias": "Wanna Marcus", "Person": "Wanna", "House": "Bene Gesserit"},
    {"Alias": "Wellington", "Person": "Yueh", "House": "Atreides"},
    {"Alias": "Wellington Yueh", "Person": "Yueh", "House": "Atreides"},
    {"Alias": "Wenn", "Person": "Wensicia", "House": "Corrino"},
    {"Alias": "Wensicia", "Person": "Wensicia", "House": "Corrino"},
    {"Alias": "YUEH", "Person": "Yueh", "House": "Atreides"},
    {"Alias": "Yakup Abad", "Person": "Yakup Abad", "House": "Atreides"},
    {"Alias": "Yanshuph Ashkoko", "Person": "Yanshuph Ashkoko", "House": "Unknown"},
    {"Alias": "Yueh", "Person": "Yueh", "House": "Atreides"},
    {"Alias": "Zebataleph", "Person": "Zebataleph", "House": "Fremen"},
    {"Alias": "Zia", "Person": "Ziamad", "House": "Bene Gesserit"},
    {"Alias": "Ziamad", "Person": "Ziamad", "House": "Bene Gesserit"},
    {"Alias": "Ziarenka", "Person": "Ziarenka Valefor", "House": "Atreidis"},
    {"Alias": "Ziarenka Valefor", "Person": "Ziarenka Valefor", "House": "Atreidis"},
    {"Alias": "Ziarenko Javid", "Person": "Ziarenko Javid", "House": "Fremen"},
    {"Alias": "a Lisan al-Gaib", "Person": "Paul", "House": "Atreidis"},
    {"Alias": "a Paul Atreides", "Person": "Paul", "House": "Atreidis"},
    {"Alias": "al-Fali", "Person": "Ghadhean", "House": "Fremen"},
    {"Alias": "al-Fali's", "Person": "Ghadhean", "House": "Fremen"},
    {"Alias": "al-Gaib", "Person": "Paul", "House": "Atreidis"},
    {"Alias": "ghanima", "Person": "Ghanima", "House": "Atreidis"},
    {"Alias": "the Angel of Death", "Person": "Al-Baz", "House": "Fremen"},
    {"Alias": "the Atreides Duke", "Person": "Leto I", "House": "Atreidis"},
    {"Alias": "the Bashar Abulurd Harkonnen", "Person": "Abulurd", "House": "Harkonnen"},
    {"Alias": "the Bashar Tyekanik", "Person": "the Bashar Tyekanik", "House": "Corrino"},
    {"Alias": "the Beast Rabban", "Person": "Glossu", "House": "Harkonnen"},
    {"Alias": "the Fedaykin Tandis", "Person": "Tandis", "House": "Fremen"},
    {"Alias": "the Great Mother", "Person": "Jessica", "House": "Atreidis"},
    {"Alias": "the Kwisatz Haderach", "Person": "Paul", "House": "Atreidis"},
    {"Alias": "the Lady Jessica", "Person": "Jessica", "House": "Atreidis"},
    {"Alias": "the Lisan", "Person": "Paul", "House": "Atreidis"},
    {"Alias": "the Lisan al-Gaib", "Person": "Paul", "House": "Atreidis"},
    {"Alias": "the Mentat Duncan", "Person": "Duncan", "House": "Atreidis"},
    {"Alias": "the Mentat-Assassin", "Person": "Hawat", "House": "Atreides"},
    {"Alias": "the Mudir Nahya", "Person": "Glossu", "House": "Harkonnen"},
    {"Alias": "the Old Baron", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "the Old Duke", "Person": "Leto I", "House": "Atreidis"},
    {"Alias": "the Padishah Emperor", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "the Padishah Shaddam IV", "Person": "E. Shaddam", "House": "Corrino"},
    {"Alias": "the Princess Irulan", "Person": "Irulan", "House": "Corrino"},
    {"Alias": "the Princess Irulan", "Person": "Irulan", "House": "Corrino"},
    {"Alias": "the Shadout Mapes", "Person": "Mapes", "House": "Atreides"},
    {"Alias": "the Siridar-Baron", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "the Siridar-Baron's", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "the Voice from the Outer World", "Person": "Paul", "House": "Atreidis"},
    {"Alias": "the Water Sellers", "Person": "Lingar Bewt", "House": "Arrakis Water seller"},
    {"Alias": "the Womb of Heaven", "Person": "Alia", "House": "Atreides"},
    {"Alias": "the na-Baron", "Person": "Vladimir", "House": "Harkonnen"},
    {"Alias": "this Buer Agarves", "Person": "Buer Agarves", "House": "Fremen"},
    {"Alias": "this Corrino Prince", "Person": "Farad'n", "House": "Corrino"},
    {"Alias": "this Kwisatz Haderach", "Person": "Paul", "House": "Atreides"},
    {"Alias": "this Liet-Kynes", "Person": "Liet-Kynes", "House": "Fremen"},
    {"Alias": "this Muad'Dib.", "Person": "Paul", "House": "Atreides"},
    {"Alias": "this Tagir Mohandis", "Person": "Tagir Mohandis", "House": "Bene Gesserit"}
]

In [ ]:
filtered_df.head(15)

,book,sentence,person_entities
15,Book 1,Paul's mother answered in her soft contralto: ...,"Paul, Atreides"
45,Book 1,Now the Harkonnens were leaving to be replaced...,"Harkonnens, Leto"
46,Book 1,"Yet, Hawat had said, this appearance contained...","Hawat, Leto"
133,Book 1,"Jessica's hand went to Paul's shoulder, tighte...","Jessica, Paul"
140,Book 1,The old woman studied Paul in one gestalten fl...,"Paul, Jessica, Duke"
149,Book 1,Jessica took her hand from Paul's shoulder.,"Jessica, Paul"
465,Book 1,"""Paul,"" Jessica said.","Paul, Jessica"
520,Book 1,"""Observe closely, Piter, and you, too, Feyd-Ra...","Piter, Feyd-Rautha"
579,Book 1,It is to see a plan of the most exquisite trea...,"Leto, Caladan, Dune"
621,Book 1,"Dr. Yueh will move against him soon, and that'...","Yueh, Atreides"
644,Book 1,"""\n Piter took five curiously mincing steps...","Piter, Feyd-Rautha"
647,Book 1,"""Do not toy with Piter, Baron,"" Piter said.","Piter, Piter"
660,Book 1,"""What of the Dukeling, the child Paul, my dear...","Paul, Piter"
661,Book 1,"""The trap will bring him to you, Baron,"" Piter...","Baron, Piter"
667,Book 1,"""I'm not often wrong, Baron,"" Piter said, and ...","Baron, Piter"

In [ ]:
# Create a DataFrame for the mapping data
mapping_df = pd.DataFrame(mapping_data)

# Split the 'person_entities' column into individual names
expanded_df = (
    filtered_df.assign(person_entities=filtered_df["person_entities"].str.split(", "))
    .explode("person_entities")
    .reset_index(drop=True)
)

# Perform the mapping on the expanded DataFrame
merged_df = expanded_df.merge(mapping_df, left_on="person_entities", right_on="Alias", how="left")

# Drop rows where mapping was not found
filtered_df_mapped = merged_df.dropna(subset=["Person"])

# Drop unnecessary columns and keep relevant data
final_df = filtered_df_mapped[["book", "sentence", "Person", "House"]]

final_df.head()

     book                                           sentence  Person     House
0  Book 1  Paul's mother answered in her soft contralto: ...    Paul  Atreides
1  Book 1  Paul's mother answered in her soft contralto: ...    Paul  Atreides
4  Book 1  Now the Harkonnens were leaving to be replaced...  Leto I  Atreides
5  Book 1  Yet, Hawat had said, this appearance contained...   Hawat  Atreides
6  Book 1  Yet, Hawat had said, this appearance contained...  Leto I  Atreides

In [ ]:
final_df.head(15)

,book,sentence,Person,House
0,Book 1,Paul's mother answered in her soft contralto: ...,Paul,Atreides
1,Book 1,Paul's mother answered in her soft contralto: ...,Paul,Atreides
4,Book 1,Now the Harkonnens were leaving to be replaced...,Leto I,Atreides
5,Book 1,"Yet, Hawat had said, this appearance contained...",Hawat,Atreides
6,Book 1,"Yet, Hawat had said, this appearance contained...",Leto I,Atreides
7,Book 1,"Jessica's hand went to Paul's shoulder, tighte...",Jessica,Fremen
8,Book 1,"Jessica's hand went to Paul's shoulder, tighte...",Paul,Atreides
9,Book 1,"Jessica's hand went to Paul's shoulder, tighte...",Paul,Atreides
10,Book 1,The old woman studied Paul in one gestalten fl...,Paul,Atreides
11,Book 1,The old woman studied Paul in one gestalten fl...,Paul,Atreides
12,Book 1,The old woman studied Paul in one gestalten fl...,Jessica,Fremen
13,Book 1,The old woman studied Paul in one gestalten fl...,Leto I,Atreides
14,Book 1,Jessica took her hand from Paul's shoulder.,Jessica,Fremen
15,Book 1,Jessica took her hand from Paul's shoulder.,Paul,Atreides
16,Book 1,Jessica took her hand from Paul's shoulder.,Paul,Atreides

In [ ]:
# we see Leto is the only ont talking, nobody there, so we'll remove those
# Count occurrences of each sentence
sentence_counts = final_df['sentence'].value_counts()

# Filter to retain only sentences that occur more than once
valid_sentences = sentence_counts[sentence_counts > 1].index

# Filter the DataFrame to include only rows with these sentences
final_df = final_df[final_df['sentence'].isin(valid_sentences)]

In [ ]:
final_df.shape

(5554, 4)

In [ ]:
final_df.head(15)

,book,sentence,Person,House
0,Book 1,Paul's mother answered in her soft contralto: ...,Paul,Atreides
1,Book 1,Paul's mother answered in her soft contralto: ...,Paul,Atreides
5,Book 1,"Yet, Hawat had said, this appearance contained...",Hawat,Atreides
6,Book 1,"Yet, Hawat had said, this appearance contained...",Leto I,Atreides
7,Book 1,"Jessica's hand went to Paul's shoulder, tighte...",Jessica,Fremen
8,Book 1,"Jessica's hand went to Paul's shoulder, tighte...",Paul,Atreides
9,Book 1,"Jessica's hand went to Paul's shoulder, tighte...",Paul,Atreides
10,Book 1,The old woman studied Paul in one gestalten fl...,Paul,Atreides
11,Book 1,The old woman studied Paul in one gestalten fl...,Paul,Atreides
12,Book 1,The old woman studied Paul in one gestalten fl...,Jessica,Fremen
13,Book 1,The old woman studied Paul in one gestalten fl...,Leto I,Atreides
14,Book 1,Jessica took her hand from Paul's shoulder.,Jessica,Fremen
15,Book 1,Jessica took her hand from Paul's shoulder.,Paul,Atreides
16,Book 1,Jessica took her hand from Paul's shoulder.,Paul,Atreides
17,Book 1,"""Paul,"" Jessica said.",Paul,Atreides

In [ ]:
final_df = final_df.drop_duplicates()

In [ ]:
final_df.shape

(4137, 4)

In [ ]:
final_df.head(15)

,book,sentence,Person,House
0,Book 1,Paul's mother answered in her soft contralto: ...,Paul,Atreides
5,Book 1,"Yet, Hawat had said, this appearance contained...",Hawat,Atreides
6,Book 1,"Yet, Hawat had said, this appearance contained...",Leto I,Atreides
7,Book 1,"Jessica's hand went to Paul's shoulder, tighte...",Jessica,Fremen
8,Book 1,"Jessica's hand went to Paul's shoulder, tighte...",Paul,Atreides
10,Book 1,The old woman studied Paul in one gestalten fl...,Paul,Atreides
12,Book 1,The old woman studied Paul in one gestalten fl...,Jessica,Fremen
13,Book 1,The old woman studied Paul in one gestalten fl...,Leto I,Atreides
14,Book 1,Jessica took her hand from Paul's shoulder.,Jessica,Fremen
15,Book 1,Jessica took her hand from Paul's shoulder.,Paul,Atreides
17,Book 1,"""Paul,"" Jessica said.",Paul,Atreides
19,Book 1,"""Paul,"" Jessica said.",Jessica,Fremen
20,Book 1,"""Observe closely, Piter, and you, too, Feyd-Ra...",Piter,Atreides
21,Book 1,"""Observe closely, Piter, and you, too, Feyd-Ra...",Feyd-Rautha,Harkonnen
27,Book 1,"""\n Piter took five curiously mincing steps...",Piter,Atreides

In [ ]:
# remove single lines one more time
# Count occurrences of each sentence
sentence_counts = final_df['sentence'].value_counts()

# Filter to retain only sentences that occur more than once
valid_sentences = sentence_counts[sentence_counts > 1].index

# Filter the DataFrame to include only rows with these sentences
final_df = final_df[final_df['sentence'].isin(valid_sentences)]
final_df.head(15)

,book,sentence,Person,House
5,Book 1,"Yet, Hawat had said, this appearance contained...",Hawat,Atreides
6,Book 1,"Yet, Hawat had said, this appearance contained...",Leto I,Atreides
7,Book 1,"Jessica's hand went to Paul's shoulder, tighte...",Jessica,Fremen
8,Book 1,"Jessica's hand went to Paul's shoulder, tighte...",Paul,Atreides
10,Book 1,The old woman studied Paul in one gestalten fl...,Paul,Atreides
12,Book 1,The old woman studied Paul in one gestalten fl...,Jessica,Fremen
13,Book 1,The old woman studied Paul in one gestalten fl...,Leto I,Atreides
14,Book 1,Jessica took her hand from Paul's shoulder.,Jessica,Fremen
15,Book 1,Jessica took her hand from Paul's shoulder.,Paul,Atreides
17,Book 1,"""Paul,"" Jessica said.",Paul,Atreides
19,Book 1,"""Paul,"" Jessica said.",Jessica,Fremen
20,Book 1,"""Observe closely, Piter, and you, too, Feyd-Ra...",Piter,Atreides
21,Book 1,"""Observe closely, Piter, and you, too, Feyd-Ra...",Feyd-Rautha,Harkonnen
27,Book 1,"""\n Piter took five curiously mincing steps...",Piter,Atreides
28,Book 1,"""\n Piter took five curiously mincing steps...",Feyd-Rautha,Harkonnen

In [ ]:
final_df.shape

(3934, 4)

In [ ]:
final_df.tail(5)

,book,sentence,Person,House
6558,Book 3,"He turned, looked mockingly at Farad'n, lowere...",Farad'n,Corrino
6560,Book 3,"He turned, looked mockingly at Farad'n, lowere...",Ghani,Atreides
6561,Book 3,"Ghanima once more took Farad'n's hand, but her...",Ghani,Atreides
6562,Book 3,"Ghanima once more took Farad'n's hand, but her...",Farad'n,Corrino
6564,Book 3,"Ghanima once more took Farad'n's hand, but her...",Leto I,Atreides

In [ ]:
from itertools import combinations
import networkx as nx

# Initialize nodes and edges
nodes = set()
edges = []

# Group by sentence to find entities interacting in the same sentence
grouped = final_df.groupby("sentence")["Person"].apply(list)

# Iterate through grouped sentences
for sentence, entities in grouped.items():
    # Add nodes to the graph
    nodes.update(entities)

    # Create edges for all possible pairs of entities within the same sentence
    edges.extend(combinations(entities, 2))

# Build the graph
graph = nx.Graph()
graph.add_nodes_from(nodes)
graph.add_edges_from(edges)

In [ ]:
nodes

{'Abulurd',
 'Abumojandis',
 'Alia',
 'Aramsham',
 'Arkie',
 'Assan',
 'Bannerjee',
 'Behaleth',
 'Bijaz',
 'Bikouros',
 'Buer',
 'Buer Agarves',
 'Cahueit',
 'Chalice',
 'Chani',
 'Chatt',
 'Czigo',
 'Dalak Fenring',
 'Dhuri',
 'Djedida',
 'Duncan',
 'E. Shaddam',
 'Edric',
 'Elrood IX',
 'Esmar',
 'Essas Paymon',
 "Farad'n",
 'Farok',
 'Farrukh',
 'Feyd-Rautha',
 'Geoff',
 'Ghadhean',
 'Ghadhean al-Fali',
 'Ghani',
 'Ghanima',
 'Glossu',
 'Gurney',
 'Harah',
 'Hasimir',
 'Hawat',
 'Helen Mohaim',
 'Hobars',
 'Irulan',
 'Jamis',
 'Javid',
 'Jessica',
 'Josifa',
 'Kaleff',
 'Kinet',
 'Korba',
 'Larus',
 'Legg',
 'Leto I',
 'Leto II',
 'Lichna',
 'Liet-Kynes',
 'Lingar Bewt',
 'Lu',
 'Mapes',
 'Margot Fenring',
 'Melides',
 'Mirzabah',
 'Mitha',
 'Mohandis',
 'Muriz',
 'Naib',
 'Namri',
 'Nefud',
 'Nisai',
 'Ohashi',
 'Orlop',
 'Otheym',
 'Palimbasha',
 'Paul',
 'Piter',
 'Rajia',
 'Ramallo',
 'Rasir',
 'Rugi',
 'Saajid',
 'Sabiha',
 'Scytale',
 'Shakkad',
 'Sheba',
 'Shishakli',
 'Soo-Soo',
 'Staban',
 'Stilgar',
 'Subiay',
 'Tagir Mohandis',
 'Tandis',
 'Tasmin',
 'Tecrube',
 'Tharthar',
 "Tuek's Sietch",
 'Umman',
 'Vladimir',
 'Wanna',
 'Wensicia',
 'Yanshuph Ashkoko',
 'Yueh',
 'Zebataleph',
 'Ziamad',
 'Ziarenka Valefor',
 'Ziarenko Javid',
 'the Bashar Tyekanik'}

In [ ]:
edges

[('Gurney', 'Leto I'),
 ('Wensicia', "Tuek's Sietch"),
 ('Harah', 'Alia'),
 ('Edric', 'Scytale'),
 ('Hawat', 'Piter'),
 ('Paul', 'Korba'),
 ('Stilgar', 'Leto I'),
 ('Feyd-Rautha', 'Paul'),
 ('Irulan', 'Scytale'),
 ('Ghani', 'Helen Mohaim'),
 ('Leto I', 'Paul'),
 ('Leto I', 'Ghani'),
 ('Gurney', 'Paul'),
 ('Otheym', 'Alia'),
 ('Saajid', 'Stilgar'),
 ('Saajid', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Paul', 'Harah'),
 ('Paul', 'Bijaz'),
 ('Vladimir', 'Piter'),
 ('Jessica', 'Duncan'),
 ('Muriz', 'Leto I'),
 ('Gurney', 'Stilgar'),
 ('Gurney', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Alia', 'Irulan'),
 ('Paul', 'Mapes'),
 ('Irulan', 'Alia'),
 ('Jessica', "Tuek's Sietch"),
 ('Alia', 'Irulan'),
 ('Leto I', 'Paul'),
 ('Namri', 'Leto I'),
 ('Farok', 'Scytale'),
 ('Liet-Kynes', 'Jessica'),
 ('Liet-Kynes', "Tuek's Sietch"),
 ('Jessica', "Tuek's Sietch"),
 ('Paul', 'Yueh'),
 ('Piter', 'Feyd-Rautha'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Alia', 'Paul'),
 ('Harah', 'Stilgar'),
 ('Irulan', 'Scytale'),
 ('Essas Paymon', 'Alia'),
 ('Essas Paymon', 'Ziarenko Javid'),
 ('Alia', 'Ziarenko Javid'),
 ('Yueh', 'Irulan'),
 ('Alia', 'Leto I'),
 ('Alia', 'Stilgar'),
 ('Alia', "Farad'n"),
 ('Alia', 'Jessica'),
 ('Alia', 'Ghani'),
 ('Alia', 'Stilgar'),
 ('Ghani', 'Stilgar'),
 ('Alia', 'Jessica'),
 ('Alia', 'Irulan'),
 ('Alia', 'Paul'),
 ('Alia', 'Paul'),
 ('Alia', 'Paul'),
 ('Irulan', 'Alia'),
 ('Stilgar', 'Paul'),
 ("Tuek's Sietch", "Farad'n"),
 ('Liet-Kynes', 'Gurney'),
 ('Alia', 'Leto I'),
 ('Alia', 'Jessica'),
 ('Alia', 'Ghani'),
 ('Jessica', 'Ghani'),
 ('Duncan', 'Alia'),
 ('Ghani', 'Irulan'),
 ('Leto I', 'Jessica'),
 ('Leto I', 'Ghani'),
 ('Jessica', 'Ghani'),
 ('Leto I', 'Stilgar'),
 ('Hawat', 'Feyd-Rautha'),
 ('Glossu', 'Feyd-Rautha'),
 ('Stilgar', 'Alia'),
 ('Jessica', 'Hawat'),
 ('Namri', 'Leto I'),
 ('Paul', 'Gurney'),
 ('Hawat', 'Paul'),
 ('Scytale', 'Edric'),
 ('Stilgar', "Tuek's Sietch"),
 ('Alia', 'Stilgar'),
 ('Alia', 'Jessica'),
 ('Stilgar', 'Jessica'),
 ('Piter', 'Hasimir'),
 ('Duncan', 'Javid'),
 ('Bannerjee', 'Stilgar'),
 ('Bannerjee', 'Stilgar'),
 ('Bannerjee', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Bannerjee', 'Paul'),
 ('Vladimir', 'Leto I'),
 ('Paul', 'Jessica'),
 ('Harah', 'Stilgar'),
 ('Glossu', 'Paul'),
 ('Alia', 'Paul'),
 ('Alia', 'Edric'),
 ('Paul', 'Edric'),
 ('Bijaz', 'Dhuri'),
 ('Bijaz', 'Dhuri'),
 ('Bijaz', 'Paul'),
 ('Paul', 'Scytale'),
 ('Liet-Kynes', 'Hawat'),
 ('Liet-Kynes', 'Nefud'),
 ('Hawat', 'Nefud'),
 ('Javid', 'Alia'),
 ('Alia', 'Wensicia'),
 ("Farad'n", 'Jessica'),
 ('Otheym', 'Korba'),
 ('Yueh', 'Gurney'),
 ('Alia', 'Subiay'),
 ('Alia', 'Mitha'),
 ('Subiay', 'Mitha'),
 ('Jessica', 'Irulan'),
 ('Korba', 'Stilgar'),
 ('Edric', 'Scytale'),
 ('Paul', 'Edric'),
 ('Paul', 'Stilgar'),
 ('Edric', 'Stilgar'),
 ('Paul', 'Leto I'),
 ('Paul', 'Paul'),
 ('Leto I', 'Paul'),
 ('Jessica', 'Harah'),
 ('Piter', 'Feyd-Rautha'),
 ('Chani', 'Stilgar'),
 ('Muriz', 'Leto I'),
 ('Alia', 'Buer Agarves'),
 ('Chani', 'Tandis'),
 ('Chani', 'Stilgar'),
 ('Chani', 'Jessica'),
 ('Chani', 'Paul'),
 ('Chani', 'Paul'),
 ('Chani', 'Gurney'),
 ('Paul', 'Gurney'),
 ('Chani', 'Paul'),
 ('Paul', 'Edric'),
 ('Otheym', 'Dhuri'),
 ('Paul', 'Korba'),
 ('Paul', 'Stilgar'),
 ('Lichna', 'Otheym'),
 ('Lichna', 'Dhuri'),
 ('Otheym', 'Dhuri'),
 ('Leto I', 'Stilgar'),
 ('Paul', 'Irulan'),
 ('Sabiha', 'Leto I'),
 ('Edric', 'Paul'),
 ('Paul', 'Stilgar'),
 ('Yueh', 'Jessica'),
 ('Liet-Kynes', 'Paul'),
 ('Paul', 'Farok'),
 ('Paul', 'Edric'),
 ('Scytale', 'Edric'),
 ('Ghani', 'Harah'),
 ('Paul', 'Gurney'),
 ('Duncan', 'Paul'),
 ('Duncan', 'Alia'),
 ('Duncan', 'Gurney'),
 ('Duncan', 'Jessica'),
 ('Duncan', 'Paul'),
 ('Duncan', 'Paul'),
 ('Duncan', 'Gurney'),
 ('Paul', 'Gurney'),
 ('Duncan', 'Paul'),
 ('Duncan', 'Paul'),
 ('Duncan', 'Alia'),
 ('Duncan', 'Leto I'),
 ('Edric', 'Scytale'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Yueh'),
 ('Hawat', 'Jessica'),
 ('Paul', 'Irulan'),
 ('Paul', "Farad'n"),
 ('Irulan', "Farad'n"),
 ('Paul', 'Alia'),
 ('Vladimir', 'Glossu'),
 ('Paul', 'Chani'),
 ('Paul', 'Stilgar'),
 ('Chani', 'Stilgar'),
 ('Ghani', 'Alia'),
 ('Ghani', 'Stilgar'),
 ('Assan', 'Leto I'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Jessica'),
 ('Gurney', 'Chani'),
 ('Gurney', 'Paul'),
 ('Chani', 'Paul'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Leto I'),
 ('Gurney', 'Paul'),
 ('Korba', 'Naib'),
 ('Korba', 'Paul'),
 ('Naib', 'Paul'),
 ('Harah', 'Paul'),
 ('Bannerjee', 'Stilgar'),
 ('Hawat', 'Paul'),
 ('Ghani', 'Stilgar'),
 ("Farad'n", 'Jessica'),
 ('Paul', 'Chani'),
 ('Paul', 'Gurney'),
 ('Stilgar', 'Ghani'),
 ('Otheym', 'Bijaz'),
 ('Stilgar', 'Paul'),
 ('Paul', 'Scytale'),
 ('Buer', 'Buer Agarves'),
 ('Gurney', 'Paul'),
 ('Alia', 'Ghani'),
 ('Duncan', 'Gurney'),
 ('Duncan', 'Hawat'),
 ('Gurney', 'Hawat'),
 ('Namri', 'Leto I'),
 ('Alia', 'Leto I'),
 ('Alia', 'Jessica'),
 ('Alia', 'Paul'),
 ('Leto I', 'Jessica'),
 ('Leto I', 'Paul'),
 ('Jessica', 'Paul'),
 ('Chani', 'Liet-Kynes'),
 ('Farok', 'Scytale'),
 ('Namri', 'Javid'),
 ('Otheym', 'Lichna'),
 ('Staban', 'Esmar'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Edric'),
 ('Stilgar', 'Edric'),
 ('Stilgar', 'Paul'),
 ('Leto I', 'Piter'),
 ('Leto I', 'Paul'),
 ('Helen Mohaim', 'Scytale'),
 ("Farad'n", 'Jessica'),
 ('Duncan', 'Hawat'),
 ('Ramallo', 'Jessica'),
 ('Ghadhean', 'Jessica'),
 ('Subiay', 'Alia'),
 ('Javid', 'Leto I'),
 ('Gurney', 'Leto I'),
 ('Chani', 'Harah'),
 ('Stilgar', 'Leto I'),
 ('Stilgar', 'Paul'),
 ('Farok', 'Stilgar'),
 ('Alia', 'Harah'),
 ('Chani', 'Harah'),
 ('Leto I', 'Namri'),
 ('Alia', 'Irulan'),
 ('Alia', 'Ghani'),
 ('Irulan', 'Ghani'),
 ('Duncan', 'Leto I'),
 ('Alia', 'Leto I'),
 ('Alia', 'Ghani'),
 ('Leto I', 'Ghani'),
 ('Jessica', 'Paul'),
 ('Alia', 'Irulan'),
 ('Namri', 'Gurney'),
 ('Jamis', 'Paul'),
 ('Paul', 'Leto I'),
 ('Jessica', "Farad'n"),
 ('Chani', 'Jamis'),
 ('Stilgar', 'Harah'),
 ('Stilgar', 'Paul'),
 ('Harah', 'Paul'),
 ('Leto I', 'Paul'),
 ('Gurney', 'Jessica'),
 ('Vladimir', 'Piter'),
 ('Ghani', 'Irulan'),
 ('Ghani', 'Alia'),
 ('Irulan', 'Alia'),
 ('Jessica', 'Leto I'),
 ('Leto I', 'Leto II'),
 ("Tuek's Sietch", "Farad'n"),
 ('Alia', 'Ghani'),
 ('Hawat', 'Feyd-Rautha'),
 ('Irulan', 'Stilgar'),
 ('Stilgar', 'Paul'),
 ('Paul', 'Chani'),
 ('Stilgar', 'Leto I'),
 ('Stilgar', 'Alia'),
 ('Leto I', 'Alia'),
 ('Jamis', 'Stilgar'),
 ('Paul', 'Jessica'),
 ('Yueh', 'Piter'),
 ('Yueh', 'Hawat'),
 ('Piter', 'Hawat'),
 ('Ghani', 'Stilgar'),
 ('Gurney', 'Jessica'),
 ('Chani', 'Paul'),
 ('Irulan', 'Paul'),
 ('Irulan', 'Paul'),
 ('Irulan', 'Paul'),
 ('Duncan', 'Paul'),
 ('Ghani', 'Alia'),
 ('Jessica', 'Gurney'),
 ('Paul', 'Stilgar'),
 ('Alia', 'Leto I'),
 ('Jessica', 'Alia'),
 ('Czigo', 'Kinet'),
 ('Otheym', 'Korba'),
 ('Otheym', 'Paul'),
 ('Paul', 'Jessica'),
 ('Mapes', 'Stilgar'),
 ('Harah', 'Alia'),
 ('Duncan', 'Paul'),
 ('Liet-Kynes', 'Stilgar'),
 ('Stilgar', 'Paul'),
 ('Gurney', 'Jessica'),
 ('Duncan', 'Paul'),
 ('Paul', 'Leto I'),
 ('Namri', 'Leto I'),
 ('Jamis', 'Chani'),
 ('Javid', 'Alia'),
 ('Javid', 'Jessica'),
 ('Javid', "Farad'n"),
 ('Jessica', 'Paul'),
 ('Jessica', 'Ghani'),
 ('Korba', 'Stilgar'),
 ('Korba', 'Paul'),
 ('Korba', 'Paul'),
 ('Larus', 'Farrukh'),
 ("Tuek's Sietch", "Farad'n"),
 ('Paul', 'Jessica'),
 ('Leto I', 'Ghani'),
 ('Leto I', 'Javid'),
 ('Leto I', 'Ghani'),
 ('Javid', 'Ghani'),
 ('Leto I', 'Ghani'),
 ('Lichna', 'Dhuri'),
 ('Lichna', 'Paul'),
 ('Stilgar', 'Alia'),
 ('Paul', 'Gurney'),
 ('Czigo', 'Jessica'),
 ('Stilgar', 'Paul'),
 ('Alia', 'Gurney'),
 ('Alia', 'Jessica'),
 ('Gurney', 'Jessica'),
 ('Lingar Bewt', 'Liet-Kynes'),
 ('Helen Mohaim', 'Kinet'),
 ('Paul', 'Chani'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Farok'),
 ('Stilgar', 'Ziamad'),
 ('Vladimir', 'Nefud'),
 ('Irulan', 'Paul'),
 ("Tuek's Sietch", "Farad'n"),
 ("Tuek's Sietch", "Farad'n"),
 ('Stilgar', 'Leto I'),
 ('Hawat', 'Duncan'),
 ('Stilgar', 'Paul'),
 ('Scytale', 'Chani'),
 ('Paul', "Farad'n"),
 ('Gurney', 'Paul'),
 ('Paul', 'Stilgar'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Jessica'),
 ('Paul', 'Jessica'),
 ('Gurney', 'Jessica'),
 ('Javid', 'Jessica'),
 ('Scytale', 'Farok'),
 ('Jessica', 'Hawat'),
 ('Vladimir', 'Paul'),
 ('Paul', 'Stilgar'),
 ("Farad'n", 'Jessica'),
 ('Piter', 'Feyd-Rautha'),
 ('Paul', 'Jessica'),
 ('Otheym', 'Alia'),
 ('Otheym', 'Paul'),
 ('Otheym', 'Paul'),
 ('Otheym', 'Dhuri'),
 ('Paul', 'Dhuri'),
 ('Otheym', 'Farok'),
 ('Alia', 'Jessica'),
 ('Alia', 'Naib'),
 ('Jessica', 'Naib'),
 ('Edric', 'Scytale'),
 ('Paul', 'Edric'),
 ('Paul', 'Jessica'),
 ('Paul', 'Jessica'),
 ('Paul', 'Jessica'),
 ('Paul', 'Jessica'),
 ('Paul', 'Jessica'),
 ('Paul', 'Alia'),
 ('Paul', 'Jessica'),
 ('Leto I', 'Alia'),
 ("Farad'n", "Tuek's Sietch"),
 ('Gurney', 'Paul'),
 ("Farad'n", 'Alia'),
 ('Scytale', 'Edric'),
 ('Jessica', 'Irulan'),
 ('Korba', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Otheym', 'Paul'),
 ('Helen Mohaim', 'Paul'),
 ('Jessica', 'Tharthar'),
 ('Jessica', 'Stilgar'),
 ('Tharthar', 'Stilgar'),
 ('Harah', 'Paul'),
 ('Paul', 'Jessica'),
 ('Duncan', 'Jessica'),
 ('Duncan', 'Leto I'),
 ('Jessica', 'Leto I'),
 ('Jessica', 'Chani'),
 ('Scytale', 'Irulan'),
 ('Chani', 'Tandis'),
 ('Leto I', 'Ghani'),
 ('Chani', 'Paul'),
 ('Liet-Kynes', 'Jessica'),
 ('Hawat', 'Liet-Kynes'),
 ('Tandis', 'Lichna'),
 ('Duncan', 'Scytale'),
 ('Javid', 'Jessica'),
 ('Hawat', 'Bijaz'),
 ('Paul', 'Irulan'),
 ('Ghani', "Farad'n"),
 ('Ghani', 'Jessica'),
 ("Farad'n", 'Jessica'),
 ('Gurney', 'Namri'),
 ('Paul', 'Korba'),
 ('Paul', 'Stilgar'),
 ('Korba', 'Stilgar'),
 ('Stilgar', 'Paul'),
 ('Jessica', 'Paul'),
 ('Duncan', 'Alia'),
 ('Duncan', 'Paul'),
 ('Stilgar', 'Chani'),
 ('Stilgar', 'Gurney'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Leto I'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Leto I'),
 ('Paul', 'Leto I'),
 ('Stilgar', 'Duncan'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Ghani'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Jamis'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Jessica'),
 ('Stilgar', 'Alia'),
 ('Stilgar', 'Gurney'),
 ('Stilgar', 'Alia'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Gurney'),
 ('Stilgar', 'Jamis'),
 ('Chani', 'Paul'),
 ('Jessica', 'Piter'),
 ('Stilgar', 'Chani'),
 ('Paul', 'Gurney'),
 ('Chani', 'Jessica'),
 ('Gurney', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Gurney'),
 ('Stilgar', 'Leto I'),
 ('Gurney', 'Leto I'),
 ('Stilgar', 'Paul'),
 ('Ghani', 'Irulan'),
 ('Alia', 'Irulan'),
 ('Stilgar', 'Jessica'),
 ('Paul', 'Alia'),
 ('Paul', 'Stilgar'),
 ('Stilgar', 'Paul'),
 ('Jessica', 'Stilgar'),
 ('Jessica', 'Chani'),
 ('Jessica', 'Liet-Kynes'),
 ('Stilgar', 'Chani'),
 ('Stilgar', 'Liet-Kynes'),
 ('Chani', 'Liet-Kynes'),
 ('Paul', 'Gurney'),
 ('Otheym', 'Paul'),
 ('Leto I', 'Piter'),
 ('Ghani', 'Leto I'),
 ('Helen Mohaim', 'Korba'),
 ('Gurney', 'Jessica'),
 ('Jessica', 'Leto I'),
 ('Javid', 'Jessica'),
 ('Helen Mohaim', 'Farok'),
 ('Gurney', 'Duncan'),
 ('Ghani', 'Jessica'),
 ('Yueh', 'Paul'),
 ('Korba', 'Paul'),
 ('Jamis', 'Stilgar'),
 ('Farok', 'Scytale'),
 ('Stilgar', 'Alia'),
 ('Piter', 'Vladimir'),
 ('Jamis', 'Stilgar'),
 ('Vladimir', 'Irulan'),
 ('Gurney', 'Chani'),
 ('Jamis', 'Harah'),
 ('Paul', 'Alia'),
 ('Jamis', 'Paul'),
 ('Jamis', 'Stilgar'),
 ('Paul', 'Stilgar'),
 ('Vladimir', 'Piter'),
 ('Gurney', 'Paul'),
 ('Jessica', 'Mohandis'),
 ('Jessica', 'Alia'),
 ('Mohandis', 'Alia'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Tharthar'),
 ('Stilgar', 'Tharthar'),
 ('Duncan', 'Jessica'),
 ('Stilgar', 'Ghani'),
 ('Paul', 'Mapes'),
 ('Liet-Kynes', 'Farok'),
 ("Farad'n", 'Ghani'),
 ('Duncan', 'Paul'),
 ('Hawat', 'Paul'),
 ('Hawat', 'Bijaz'),
 ('Liet-Kynes', 'Leto I'),
 ('Leto I', 'Ghani'),
 ('Alia', 'Irulan'),
 ('Alia', 'Duncan'),
 ('Jamis', 'Chani'),
 ('Leto I', 'Liet-Kynes'),
 ("Tuek's Sietch", "Farad'n"),
 ("Tuek's Sietch", "Farad'n"),
 ('Liet-Kynes', 'Paul'),
 ('Alia', "Farad'n"),
 ('Chani', 'Paul'),
 ('Alia', 'Jessica'),
 ('Vladimir', 'Jessica'),
 ('Edric', 'Stilgar'),
 ('Paul', 'Farok'),
 ('Hawat', 'Jessica'),
 ('Hawat', 'Paul'),
 ('Hawat', 'Paul'),
 ('Hawat', 'Paul'),
 ('Hawat', 'Leto I'),
 ('Hawat', 'Paul'),
 ('Paul', 'Chani'),
 ('Jessica', 'Chani'),
 ('Paul', 'Chani'),
 ("Farad'n", 'Mohandis'),
 ('Paul', 'Liet-Kynes'),
 ('Paul', 'Naib'),
 ("Tuek's Sietch", 'Jessica'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Jamis'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Chani'),
 ('Paul', 'Korba'),
 ('Buer Agarves', 'Stilgar'),
 ('Paul', 'Helen Mohaim'),
 ('Jamis', 'Stilgar'),
 ('Liet-Kynes', 'Leto I'),
 ('Korba', 'Paul'),
 ('Liet-Kynes', 'Alia'),
 ('Alia', 'Ghadhean'),
 ('Leto I', 'Hawat'),
 ('Gurney', "Tuek's Sietch"),
 ('Stilgar', 'Ghani'),
 ('Leto I', 'Jessica'),
 ('Paul', 'Gurney'),
 ('Paul', 'Liet-Kynes'),
 ('Gurney', 'Liet-Kynes'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Ghani'),
 ('Scytale', 'Edric'),
 ('Irulan', 'Paul'),
 ('Paul', 'Chani'),
 ('Aramsham', 'Paul'),
 ('Feyd-Rautha', 'Hawat'),
 ('Gurney', 'Paul'),
 ('Paul', 'Irulan'),
 ('Duncan', 'Jessica'),
 ('Glossu', 'Hawat'),
 ('Stilgar', 'Irulan'),
 ('Alia', 'Jessica'),
 ('Alia', 'Jessica'),
 ('Duncan', 'Gurney'),
 ('Paul', 'Piter'),
 ('Bijaz', 'Paul'),
 ('Chani', 'Paul'),
 ('Gurney', 'Paul'),
 ('Paul', 'Leto I'),
 ('Glossu', 'Paul'),
 ('Chani', 'Paul'),
 ('Muriz', 'Leto I'),
 ('Liet-Kynes', 'Jessica'),
 ('Chani', 'Paul'),
 ('Chani', 'Paul'),
 ('Paul', 'Alia'),
 ('Stilgar', 'Alia'),
 ('Liet-Kynes', 'Paul'),
 ('Stilgar', 'Harah'),
 ('Duncan', 'Paul'),
 ('Gurney', 'Leto I'),
 ('Namri', 'Leto I'),
 ('Hawat', 'Jessica'),
 ('Alia', 'Jessica'),
 ('Alia', 'Vladimir'),
 ('Farok', 'Paul'),
 ('Alia', 'Ghani'),
 ('Stilgar', 'Paul'),
 ('Paul', 'Gurney'),
 ('Chani', 'Paul'),
 ('Irulan', 'Ghani'),
 ('Alia', 'Irulan'),
 ('Wensicia', "Tuek's Sietch"),
 ('Wensicia', 'Jessica'),
 ('Wensicia', "Farad'n"),
 ('Jessica', "Farad'n"),
 ('Paul', 'Liet-Kynes'),
 ('Irulan', 'Chani'),
 ('Alia', 'Leto I'),
 ('Stilgar', 'Paul'),
 ('Ziamad', "Farad'n"),
 ('Alia', 'Paul'),
 ('Gurney', 'Paul'),
 ('Paul', 'Stilgar'),
 ('Jessica', 'Mapes'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Stilgar'),
 ('Ghani', 'Alia'),
 ('Ghani', 'Irulan'),
 ('Alia', 'Irulan'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Korba'),
 ('Scytale', 'Irulan'),
 ('Gurney', 'Leto I'),
 ('Namri', 'Gurney'),
 ('Gurney', 'Paul'),
 ('Jessica', 'Wensicia'),
 ('Jessica', "Farad'n"),
 ('Wensicia', "Farad'n"),
 ('Bijaz', 'Dhuri'),
 ('Paul', 'Harah'),
 ('Paul', 'Jessica'),
 ('Jamis', 'Stilgar'),
 ('Stilgar', 'Jamis'),
 ('Gurney', 'Leto I'),
 ('Ghani', "Farad'n"),
 ('Vladimir', 'Piter'),
 ('Stilgar', 'Leto I'),
 ('Lichna', 'Dhuri'),
 ('Irulan', 'Alia'),
 ('Duncan', 'Jessica'),
 ('Alia', 'Wensicia'),
 ('Alia', 'Ghani'),
 ('Glossu', 'Bijaz'),
 ('Paul', 'Jessica'),
 ('Hawat', 'Jessica'),
 ('Hawat', 'Liet-Kynes'),
 ('Paul', 'Bijaz'),
 ('Bannerjee', 'Paul'),
 ('Irulan', 'Ghani'),
 ('Ghani', 'Stilgar'),
 ('Irulan', 'Alia'),
 ('Alia', 'Jessica'),
 ('Duncan', 'Paul'),
 ('Vladimir', 'Paul'),
 ('Hawat', 'Liet-Kynes'),
 ('Hawat', 'Feyd-Rautha'),
 ('Yueh', 'Gurney'),
 ('Irulan', 'Yueh'),
 ('Irulan', 'Paul'),
 ('Yueh', 'Paul'),
 ('Hasimir', 'Elrood IX'),
 ('Irulan', 'Vladimir'),
 ('Edric', 'Paul'),
 ('Paul', 'Leto I'),
 ('Jamis', 'Irulan'),
 ('Jamis', 'Leto I'),
 ('Irulan', 'Leto I'),
 ('Leto II', "Farad'n"),
 ('Leto I', "Farad'n"),
 ('Leto I', 'Alia'),
 ("Farad'n", 'Alia'),
 ('Liet-Kynes', 'Jessica'),
 ('Irulan', 'Jessica'),
 ('Irulan', 'Paul'),
 ('Jessica', 'Paul'),
 ('Lu', 'Leto I'),
 ('Stilgar', 'Irulan'),
 ('Tagir Mohandis', 'Leto I'),
 ("Farad'n", "Tuek's Sietch"),
 ('Paul', 'Alia'),
 ('Leto I', 'Ghani'),
 ("Farad'n", 'Gurney'),
 ("Farad'n", 'Buer Agarves'),
 ('Paul', "Farad'n"),
 ("Farad'n", 'Leto I'),
 ('Irulan', 'Jessica'),
 ('Irulan', 'Hawat'),
 ('Irulan', 'Paul'),
 ('Irulan', 'Paul'),
 ('Irulan', 'Hawat'),
 ('Irulan', 'Stilgar'),
 ('Irulan', 'Yueh'),
 ('Irulan', 'Mapes'),
 ('Yueh', 'Mapes'),
 ('E. Shaddam', 'Leto I'),
 ('Irulan', 'Paul'),
 ('Leto I', 'Irulan'),
 ('Leto I', 'Vladimir'),
 ('Irulan', 'Vladimir'),
 ('Yanshuph Ashkoko', 'Shakkad'),
 ('Yanshuph Ashkoko', 'Paul'),
 ('Shakkad', 'Paul'),
 ('Ghani', "Farad'n"),
 ('Mapes', 'Jessica'),
 ('Javid', 'Alia'),
 ('Jessica', 'Ghadhean'),
 ('Gurney', 'Paul'),
 ('Leto I', 'Hawat'),
 ('Paul', 'Rasir'),
 ('Ghani', 'Alia'),
 ('Paul', 'Edric'),
 ('Gurney', 'Leto I'),
 ('Gurney', 'Namri'),
 ('Leto I', 'Namri'),
 ('Jessica', 'Chani'),
 ('Alia', 'Jessica'),
 ('Alia', 'Vladimir'),
 ('Paul', 'Gurney'),
 ('Paul', 'Leto I'),
 ('Gurney', 'Leto I'),
 ('Leto I', 'Ghani'),
 ('Gurney', 'Javid'),
 ('Jessica', 'Paul'),
 ('Jessica', 'Leto I'),
 ('Jessica', 'Ghani'),
 ('Leto I', 'Ghani'),
 ('Abulurd', 'Vladimir'),
 ('Chani', 'Paul'),
 ('Paul', 'Jessica'),
 ('Jessica', "Farad'n"),
 ('Duncan', 'Jessica'),
 ('Gurney', 'Sabiha'),
 ('Gurney', 'Jessica'),
 ('Leto I', 'Assan'),
 ('Leto I', 'Muriz'),
 ('Stilgar', 'Leto I'),
 ('Chani', 'Jessica'),
 ('Edric', 'Stilgar'),
 ('Gurney', 'Paul'),
 ('Jamis', 'Paul'),
 ('Jessica', 'Harah'),
 ('Mapes', 'Jessica'),
 ('Paul', 'Stilgar'),
 ('Tandis', 'Paul'),
 ('Liet-Kynes', 'Leto I'),
 ('Buer Agarves', 'Javid'),
 ('Buer Agarves', 'Stilgar'),
 ('Buer Agarves', 'Harah'),
 ('Buer Agarves', 'Rajia'),
 ('Stilgar', 'Harah'),
 ('Stilgar', 'Rajia'),
 ('Harah', 'Rajia'),
 ('Leto I', 'Paul'),
 ('Alia', 'Paul'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Duncan'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Duncan'),
 ('Stilgar', 'Duncan'),
 ('Ghadhean al-Fali', 'Stilgar'),
 ('Ghadhean al-Fali', 'Jessica'),
 ('Ghadhean al-Fali', 'Jessica'),
 ('Ghadhean al-Fali', 'Alia'),
 ('Ghadhean al-Fali', 'Jessica'),
 ('Ghadhean al-Fali', 'Jessica'),
 ('Ghadhean al-Fali', 'Jessica'),
 ('Alia', "Farad'n"),
 ('Alia', 'Ghani'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Essas Paymon'),
 ('Alia', 'Vladimir'),
 ('Alia', 'Jessica'),
 ('Alia', 'Tharthar'),
 ('Alia', 'Ghani'),
 ('Alia', 'Jessica'),
 ('Alia', "Farad'n"),
 ('Jessica', "Farad'n"),
 ('Alia', 'Stilgar'),
 ('Alia', 'Vladimir'),
 ('Alia', 'Duncan'),
 ('Alia', 'Leto I'),
 ('Alia', 'Irulan'),
 ('Alia', 'Ziamad'),
 ('Alia', 'Ghani'),
 ('Alia', 'Paul'),
 ('Alia', 'Buer'),
 ('Alia', 'Ziamad'),
 ('Buer', 'Ziamad'),
 ('Alia', 'Paul'),
 ('Alia', 'Chani'),
 ('Paul', 'Chani'),
 ('Alia', 'Harah'),
 ('Alia', 'Ziarenka Valefor'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Jessica'),
 ('Alia', 'Leto I'),
 ('Alia', 'Irulan'),
 ('Alia', 'Irulan'),
 ('Alia', 'Paul'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Paul'),
 ('Alia', 'Ghani'),
 ('Alia', 'Paul'),
 ('Alia', 'Jessica'),
 ('Alia', 'Jessica'),
 ('Alia', 'Jessica'),
 ('Alia', "Farad'n"),
 ('Alia', 'Namri'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Essas Paymon'),
 ('Alia', 'Leto I'),
 ('Hasimir', 'E. Shaddam'),
 ('Alia', 'Stilgar'),
 ('Jessica', 'Leto I'),
 ('Stilgar', 'Paul'),
 ('Feyd-Rautha', 'Hawat'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Paul'),
 ('Paul', 'Paul'),
 ('Hawat', 'Paul'),
 ('Irulan', 'Ghani'),
 ('Jessica', 'Gurney'),
 ('Jessica', 'Jamis'),
 ('Jessica', 'Stilgar'),
 ('Jessica', 'Jamis'),
 ('Jessica', 'Paul'),
 ('Stilgar', 'Jamis'),
 ('Stilgar', 'Paul'),
 ('Jamis', 'Paul'),
 ('Jessica', 'Piter'),
 ('Jessica', 'Duncan'),
 ('Jessica', 'Paul'),
 ('Jessica', 'Paul'),
 ('Jessica', 'Alia'),
 ('Jessica', 'Paul'),
 ('Jessica', 'Gurney'),
 ('Jessica', 'Alia'),
 ('Liet-Kynes', 'Jessica'),
 ('Liet-Kynes', 'Paul'),
 ('Jessica', 'Paul'),
 ('Liet-Kynes', 'Leto I'),
 ('Leto I', "Farad'n"),
 ('Leto I', 'Gurney'),
 ('Paul', 'Gurney'),
 ('Paul', 'Jamis'),
 ('Paul', 'Kaleff'),
 ('Paul', 'Geoff'),
 ('Kaleff', 'Geoff'),
 ('Paul', 'Chani'),
 ('Paul', 'Stilgar'),
 ('Chani', 'Stilgar'),
 ('Paul', 'Gurney'),
 ('Paul', 'Chani'),
 ('Paul', 'Gurney'),
 ('Stilgar', 'Jamis'),
 ("Tuek's Sietch", 'Jessica'),
 ("Tuek's Sietch", 'Wensicia'),
 ('Ziamad', 'Javid'),
 ('Paul', 'Leto I'),
 ('Leto I', 'Ghani'),
 ('Chani', 'Jessica'),
 ('Jessica', 'Paul'),
 ('Hawat', 'Lingar Bewt'),
 ('Hasimir', 'Vladimir'),
 ('Hasimir', 'Feyd-Rautha'),
 ('Vladimir', 'Feyd-Rautha'),
 ('Leto I', 'Alia'),
 ('Hawat', 'Lingar Bewt'),
 ('Paul', 'Vladimir'),
 ('Alia', 'Chani'),
 ('Alia', 'Paul'),
 ('Chani', 'Paul'),
 ('Jessica', 'Paul'),
 ('Jessica', 'Duncan'),
 ('Jessica', 'Gurney'),
 ('Paul', 'Duncan'),
 ('Paul', 'Gurney'),
 ('Duncan', 'Gurney'),
 ('Buer', 'Stilgar'),
 ('Paul', 'Chani'),
 ('Jessica', 'Alia'),
 ('Jessica', 'Ghani'),
 ('Alia', 'Ghani'),

In [ ]:
# formatting the nodes by adding the houses
from itertools import combinations
import networkx as nx
import matplotlib.pyplot as plt

# Initialize nodes and edges
nodes = {}
edges = []

# Group by sentence to find entities interacting in the same sentence
grouped = final_df.groupby("sentence")[["Person", "House"]].apply(lambda x: x.values.tolist())

# Iterate through grouped sentences
for sentence, entities in grouped.items():
    # Add nodes with house information
    for person, house in entities:
        nodes[person] = house

    # Create edges for all possible pairs of entities within the same sentence
    persons_in_sentence = [person for person, _ in entities]
    edges.extend(combinations(persons_in_sentence, 2))

# Build the graph
graph = nx.Graph()

# Add nodes with house information
for person, house in nodes.items():
    graph.add_node(person, house=house)

# Add edges
graph.add_edges_from(edges)

In [ ]:
nodes

{'Gurney': 'Atreides',
 'Leto I': 'Atreides',
 'Wensicia': 'Corrino',
 "Tuek's Sietch": 'Arrakis Water seller',
 'Harah': 'Fremen',
 'Alia': 'Atreides',
 'Edric': 'Corrino',
 'Scytale': 'Bene Gesserit',
 'Hawat': 'Atreides',
 'Piter': 'Atreides',
 'Paul': 'Atreides',
 'Korba': 'Fremen',
 'Stilgar': 'Atreides',
 'Feyd-Rautha': 'Harkonnen',
 'Irulan': 'Corrino',
 'Ghani': 'Atreides',
 'Helen Mohaim': 'Bene Gesserit',
 'Otheym': 'Fremen',
 'Saajid': 'Fremen',
 'Bijaz': 'Atreides',
 'Vladimir': 'Harkonnen',
 'Jessica': 'Fremen',
 'Duncan': 'Atreides',
 'Muriz': 'Fremen',
 'Mapes': 'Atreides',
 'Namri': 'Bene Gesserit',
 'Farok': 'Fremen',
 'Liet-Kynes': 'Fremen',
 'Yueh': 'Atreides',
 'Essas Paymon': 'Nebiro',
 'Ziarenko Javid': 'Fremen',
 "Farad'n": 'Corrino',
 'Glossu': 'Harkonnen',
 'Hasimir': 'Corrino',
 'Javid': 'Fremen',
 'Bannerjee': 'Atreides',
 'Dhuri': 'Fremen',
 'Nefud': 'Harkonnen',
 'Subiay': 'Fremen',
 'Mitha': 'Fremen',
 'Chani': 'Fremen',
 'Buer Agarves': 'Fremen',
 'Tandis': 'Fremen',
 'Lichna': 'Unknown',
 'Sabiha': 'Fremen',
 'Assan': 'Atreides',
 'Naib': 'Fremen',
 'Buer': 'Fremen',
 'Staban': 'Harkonnen',
 'Esmar': 'Atreides',
 'Ramallo': 'Fremen',
 'Ghadhean': 'Fremen',
 'Jamis': 'Fremen',
 'Leto II': 'Atreides',
 'Czigo': 'Harkonnen',
 'Kinet': 'Harkonnen',
 'Larus': 'Fremen',
 'Farrukh': 'Fremen',
 'Lingar Bewt': 'Arrakis Water seller',
 'Ziamad': 'Bene Gesserit',
 'Tharthar': 'Atreides',
 'Mohandis': 'Atreides',
 'Aramsham': 'Corrino',
 'Elrood IX': 'Corrino',
 'Lu': 'Unknown',
 'Tagir Mohandis': 'Bene Gesserit',
 'E. Shaddam': 'Corrino',
 'Yanshuph Ashkoko': 'Unknown',
 'Shakkad': 'Fremen',
 'Rasir': 'Fremen',
 'Abulurd': 'Harkonnen',
 'Rajia': 'Fremen',
 'Ghadhean al-Fali': 'Fremen',
 'Ziarenka Valefor': 'Atreidis',
 'Kaleff': 'Fremen',
 'Geoff': 'Fremen',
 'Dalak Fenring': 'Corrino',
 'Melides': 'Atreides',
 'Palimbasha': 'Fremen',
 'Arkie': 'Atreides',
 'the Bashar Tyekanik': 'Corrino',
 'Zebataleph': 'Fremen',
 'Chalice': 'Corrino',
 'Josifa': 'Corrino',
 'Rugi': 'Corrino',
 'Wanna': 'Bene Gesserit',
 'Ghanima': 'Atreidis',
 'Behaleth': 'Fremen',
 'Ohashi': 'Fremen',
 'Nisai': 'Fremen',
 'Mirzabah': 'Fremen',
 'Shishakli': 'Fremen',
 'Soo-Soo': 'Harkonnen',
 'Orlop': 'Fremen',
 'Umman': 'Harkonnen',
 'Tecrube': 'Fremen',
 'Hobars': 'Fremen',
 'Tasmin': 'Unknown',
 'Legg': 'Fremen',
 'Margot Fenring': 'Fenring',
 'Sheba': 'Bene Gesserit',
 'Abumojandis': 'Fremen',
 'Djedida': 'Fremen',
 'Bikouros': 'Fremen',
 'Cahueit': 'Fremen',
 'Chatt': 'Fremen'}

In [ ]:
# Convert nodes dictionary to a DataFrame
nodes_df = pd.DataFrame(list(nodes.items()), columns=['Person', 'House'])

# Display the DataFrame
print(nodes_df)

            Person                 House
0           Gurney              Atreides
1           Leto I              Atreides
2         Wensicia               Corrino
3    Tuek's Sietch  Arrakis Water seller
4            Harah                Fremen
..             ...                   ...
101    Abumojandis                Fremen
102        Djedida                Fremen
103       Bikouros                Fremen
104        Cahueit                Fremen
105          Chatt                Fremen

[106 rows x 2 columns]

In [ ]:
edges

[('Gurney', 'Leto I'),
 ('Wensicia', "Tuek's Sietch"),
 ('Harah', 'Alia'),
 ('Edric', 'Scytale'),
 ('Hawat', 'Piter'),
 ('Paul', 'Korba'),
 ('Stilgar', 'Leto I'),
 ('Feyd-Rautha', 'Paul'),
 ('Irulan', 'Scytale'),
 ('Ghani', 'Helen Mohaim'),
 ('Leto I', 'Paul'),
 ('Leto I', 'Ghani'),
 ('Gurney', 'Paul'),
 ('Otheym', 'Alia'),
 ('Saajid', 'Stilgar'),
 ('Saajid', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Paul', 'Harah'),
 ('Paul', 'Bijaz'),
 ('Vladimir', 'Piter'),
 ('Jessica', 'Duncan'),
 ('Muriz', 'Leto I'),
 ('Gurney', 'Stilgar'),
 ('Gurney', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Alia', 'Irulan'),
 ('Paul', 'Mapes'),
 ('Irulan', 'Alia'),
 ('Jessica', "Tuek's Sietch"),
 ('Alia', 'Irulan'),
 ('Leto I', 'Paul'),
 ('Namri', 'Leto I'),
 ('Farok', 'Scytale'),
 ('Liet-Kynes', 'Jessica'),
 ('Liet-Kynes', "Tuek's Sietch"),
 ('Jessica', "Tuek's Sietch"),
 ('Paul', 'Yueh'),
 ('Piter', 'Feyd-Rautha'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Alia', 'Paul'),
 ('Harah', 'Stilgar'),
 ('Irulan', 'Scytale'),
 ('Essas Paymon', 'Alia'),
 ('Essas Paymon', 'Ziarenko Javid'),
 ('Alia', 'Ziarenko Javid'),
 ('Yueh', 'Irulan'),
 ('Alia', 'Leto I'),
 ('Alia', 'Stilgar'),
 ('Alia', "Farad'n"),
 ('Alia', 'Jessica'),
 ('Alia', 'Ghani'),
 ('Alia', 'Stilgar'),
 ('Ghani', 'Stilgar'),
 ('Alia', 'Jessica'),
 ('Alia', 'Irulan'),
 ('Alia', 'Paul'),
 ('Alia', 'Paul'),
 ('Alia', 'Paul'),
 ('Irulan', 'Alia'),
 ('Stilgar', 'Paul'),
 ("Tuek's Sietch", "Farad'n"),
 ('Liet-Kynes', 'Gurney'),
 ('Alia', 'Leto I'),
 ('Alia', 'Jessica'),
 ('Alia', 'Ghani'),
 ('Jessica', 'Ghani'),
 ('Duncan', 'Alia'),
 ('Ghani', 'Irulan'),
 ('Leto I', 'Jessica'),
 ('Leto I', 'Ghani'),
 ('Jessica', 'Ghani'),
 ('Leto I', 'Stilgar'),
 ('Hawat', 'Feyd-Rautha'),
 ('Glossu', 'Feyd-Rautha'),
 ('Stilgar', 'Alia'),
 ('Jessica', 'Hawat'),
 ('Namri', 'Leto I'),
 ('Paul', 'Gurney'),
 ('Hawat', 'Paul'),
 ('Scytale', 'Edric'),
 ('Stilgar', "Tuek's Sietch"),
 ('Alia', 'Stilgar'),
 ('Alia', 'Jessica'),
 ('Stilgar', 'Jessica'),
 ('Piter', 'Hasimir'),
 ('Duncan', 'Javid'),
 ('Bannerjee', 'Stilgar'),
 ('Bannerjee', 'Stilgar'),
 ('Bannerjee', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Bannerjee', 'Paul'),
 ('Vladimir', 'Leto I'),
 ('Paul', 'Jessica'),
 ('Harah', 'Stilgar'),
 ('Glossu', 'Paul'),
 ('Alia', 'Paul'),
 ('Alia', 'Edric'),
 ('Paul', 'Edric'),
 ('Bijaz', 'Dhuri'),
 ('Bijaz', 'Dhuri'),
 ('Bijaz', 'Paul'),
 ('Paul', 'Scytale'),
 ('Liet-Kynes', 'Hawat'),
 ('Liet-Kynes', 'Nefud'),
 ('Hawat', 'Nefud'),
 ('Javid', 'Alia'),
 ('Alia', 'Wensicia'),
 ("Farad'n", 'Jessica'),
 ('Otheym', 'Korba'),
 ('Yueh', 'Gurney'),
 ('Alia', 'Subiay'),
 ('Alia', 'Mitha'),
 ('Subiay', 'Mitha'),
 ('Jessica', 'Irulan'),
 ('Korba', 'Stilgar'),
 ('Edric', 'Scytale'),
 ('Paul', 'Edric'),
 ('Paul', 'Stilgar'),
 ('Edric', 'Stilgar'),
 ('Paul', 'Leto I'),
 ('Paul', 'Paul'),
 ('Leto I', 'Paul'),
 ('Jessica', 'Harah'),
 ('Piter', 'Feyd-Rautha'),
 ('Chani', 'Stilgar'),
 ('Muriz', 'Leto I'),
 ('Alia', 'Buer Agarves'),
 ('Chani', 'Tandis'),
 ('Chani', 'Stilgar'),
 ('Chani', 'Jessica'),
 ('Chani', 'Paul'),
 ('Chani', 'Paul'),
 ('Chani', 'Gurney'),
 ('Paul', 'Gurney'),
 ('Chani', 'Paul'),
 ('Paul', 'Edric'),
 ('Otheym', 'Dhuri'),
 ('Paul', 'Korba'),
 ('Paul', 'Stilgar'),
 ('Lichna', 'Otheym'),
 ('Lichna', 'Dhuri'),
 ('Otheym', 'Dhuri'),
 ('Leto I', 'Stilgar'),
 ('Paul', 'Irulan'),
 ('Sabiha', 'Leto I'),
 ('Edric', 'Paul'),
 ('Paul', 'Stilgar'),
 ('Yueh', 'Jessica'),
 ('Liet-Kynes', 'Paul'),
 ('Paul', 'Farok'),
 ('Paul', 'Edric'),
 ('Scytale', 'Edric'),
 ('Ghani', 'Harah'),
 ('Paul', 'Gurney'),
 ('Duncan', 'Paul'),
 ('Duncan', 'Alia'),
 ('Duncan', 'Gurney'),
 ('Duncan', 'Jessica'),
 ('Duncan', 'Paul'),
 ('Duncan', 'Paul'),
 ('Duncan', 'Gurney'),
 ('Paul', 'Gurney'),
 ('Duncan', 'Paul'),
 ('Duncan', 'Paul'),
 ('Duncan', 'Alia'),
 ('Duncan', 'Leto I'),
 ('Edric', 'Scytale'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Yueh'),
 ('Hawat', 'Jessica'),
 ('Paul', 'Irulan'),
 ('Paul', "Farad'n"),
 ('Irulan', "Farad'n"),
 ('Paul', 'Alia'),
 ('Vladimir', 'Glossu'),
 ('Paul', 'Chani'),
 ('Paul', 'Stilgar'),
 ('Chani', 'Stilgar'),
 ('Ghani', 'Alia'),
 ('Ghani', 'Stilgar'),
 ('Assan', 'Leto I'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Jessica'),
 ('Gurney', 'Chani'),
 ('Gurney', 'Paul'),
 ('Chani', 'Paul'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Leto I'),
 ('Gurney', 'Paul'),
 ('Korba', 'Naib'),
 ('Korba', 'Paul'),
 ('Naib', 'Paul'),
 ('Harah', 'Paul'),
 ('Bannerjee', 'Stilgar'),
 ('Hawat', 'Paul'),
 ('Ghani', 'Stilgar'),
 ("Farad'n", 'Jessica'),
 ('Paul', 'Chani'),
 ('Paul', 'Gurney'),
 ('Stilgar', 'Ghani'),
 ('Otheym', 'Bijaz'),
 ('Stilgar', 'Paul'),
 ('Paul', 'Scytale'),
 ('Buer', 'Buer Agarves'),
 ('Gurney', 'Paul'),
 ('Alia', 'Ghani'),
 ('Duncan', 'Gurney'),
 ('Duncan', 'Hawat'),
 ('Gurney', 'Hawat'),
 ('Namri', 'Leto I'),
 ('Alia', 'Leto I'),
 ('Alia', 'Jessica'),
 ('Alia', 'Paul'),
 ('Leto I', 'Jessica'),
 ('Leto I', 'Paul'),
 ('Jessica', 'Paul'),
 ('Chani', 'Liet-Kynes'),
 ('Farok', 'Scytale'),
 ('Namri', 'Javid'),
 ('Otheym', 'Lichna'),
 ('Staban', 'Esmar'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Edric'),
 ('Stilgar', 'Edric'),
 ('Stilgar', 'Paul'),
 ('Leto I', 'Piter'),
 ('Leto I', 'Paul'),
 ('Helen Mohaim', 'Scytale'),
 ("Farad'n", 'Jessica'),
 ('Duncan', 'Hawat'),
 ('Ramallo', 'Jessica'),
 ('Ghadhean', 'Jessica'),
 ('Subiay', 'Alia'),
 ('Javid', 'Leto I'),
 ('Gurney', 'Leto I'),
 ('Chani', 'Harah'),
 ('Stilgar', 'Leto I'),
 ('Stilgar', 'Paul'),
 ('Farok', 'Stilgar'),
 ('Alia', 'Harah'),
 ('Chani', 'Harah'),
 ('Leto I', 'Namri'),
 ('Alia', 'Irulan'),
 ('Alia', 'Ghani'),
 ('Irulan', 'Ghani'),
 ('Duncan', 'Leto I'),
 ('Alia', 'Leto I'),
 ('Alia', 'Ghani'),
 ('Leto I', 'Ghani'),
 ('Jessica', 'Paul'),
 ('Alia', 'Irulan'),
 ('Namri', 'Gurney'),
 ('Jamis', 'Paul'),
 ('Paul', 'Leto I'),
 ('Jessica', "Farad'n"),
 ('Chani', 'Jamis'),
 ('Stilgar', 'Harah'),
 ('Stilgar', 'Paul'),
 ('Harah', 'Paul'),
 ('Leto I', 'Paul'),
 ('Gurney', 'Jessica'),
 ('Vladimir', 'Piter'),
 ('Ghani', 'Irulan'),
 ('Ghani', 'Alia'),
 ('Irulan', 'Alia'),
 ('Jessica', 'Leto I'),
 ('Leto I', 'Leto II'),
 ("Tuek's Sietch", "Farad'n"),
 ('Alia', 'Ghani'),
 ('Hawat', 'Feyd-Rautha'),
 ('Irulan', 'Stilgar'),
 ('Stilgar', 'Paul'),
 ('Paul', 'Chani'),
 ('Stilgar', 'Leto I'),
 ('Stilgar', 'Alia'),
 ('Leto I', 'Alia'),
 ('Jamis', 'Stilgar'),
 ('Paul', 'Jessica'),
 ('Yueh', 'Piter'),
 ('Yueh', 'Hawat'),
 ('Piter', 'Hawat'),
 ('Ghani', 'Stilgar'),
 ('Gurney', 'Jessica'),
 ('Chani', 'Paul'),
 ('Irulan', 'Paul'),
 ('Irulan', 'Paul'),
 ('Irulan', 'Paul'),
 ('Duncan', 'Paul'),
 ('Ghani', 'Alia'),
 ('Jessica', 'Gurney'),
 ('Paul', 'Stilgar'),
 ('Alia', 'Leto I'),
 ('Jessica', 'Alia'),
 ('Czigo', 'Kinet'),
 ('Otheym', 'Korba'),
 ('Otheym', 'Paul'),
 ('Paul', 'Jessica'),
 ('Mapes', 'Stilgar'),
 ('Harah', 'Alia'),
 ('Duncan', 'Paul'),
 ('Liet-Kynes', 'Stilgar'),
 ('Stilgar', 'Paul'),
 ('Gurney', 'Jessica'),
 ('Duncan', 'Paul'),
 ('Paul', 'Leto I'),
 ('Namri', 'Leto I'),
 ('Jamis', 'Chani'),
 ('Javid', 'Alia'),
 ('Javid', 'Jessica'),
 ('Javid', "Farad'n"),
 ('Jessica', 'Paul'),
 ('Jessica', 'Ghani'),
 ('Korba', 'Stilgar'),
 ('Korba', 'Paul'),
 ('Korba', 'Paul'),
 ('Larus', 'Farrukh'),
 ("Tuek's Sietch", "Farad'n"),
 ('Paul', 'Jessica'),
 ('Leto I', 'Ghani'),
 ('Leto I', 'Javid'),
 ('Leto I', 'Ghani'),
 ('Javid', 'Ghani'),
 ('Leto I', 'Ghani'),
 ('Lichna', 'Dhuri'),
 ('Lichna', 'Paul'),
 ('Stilgar', 'Alia'),
 ('Paul', 'Gurney'),
 ('Czigo', 'Jessica'),
 ('Stilgar', 'Paul'),
 ('Alia', 'Gurney'),
 ('Alia', 'Jessica'),
 ('Gurney', 'Jessica'),
 ('Lingar Bewt', 'Liet-Kynes'),
 ('Helen Mohaim', 'Kinet'),
 ('Paul', 'Chani'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Farok'),
 ('Stilgar', 'Ziamad'),
 ('Vladimir', 'Nefud'),
 ('Irulan', 'Paul'),
 ("Tuek's Sietch", "Farad'n"),
 ("Tuek's Sietch", "Farad'n"),
 ('Stilgar', 'Leto I'),
 ('Hawat', 'Duncan'),
 ('Stilgar', 'Paul'),
 ('Scytale', 'Chani'),
 ('Paul', "Farad'n"),
 ('Gurney', 'Paul'),
 ('Paul', 'Stilgar'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Jessica'),
 ('Paul', 'Jessica'),
 ('Gurney', 'Jessica'),
 ('Javid', 'Jessica'),
 ('Scytale', 'Farok'),
 ('Jessica', 'Hawat'),
 ('Vladimir', 'Paul'),
 ('Paul', 'Stilgar'),
 ("Farad'n", 'Jessica'),
 ('Piter', 'Feyd-Rautha'),
 ('Paul', 'Jessica'),
 ('Otheym', 'Alia'),
 ('Otheym', 'Paul'),
 ('Otheym', 'Paul'),
 ('Otheym', 'Dhuri'),
 ('Paul', 'Dhuri'),
 ('Otheym', 'Farok'),
 ('Alia', 'Jessica'),
 ('Alia', 'Naib'),
 ('Jessica', 'Naib'),
 ('Edric', 'Scytale'),
 ('Paul', 'Edric'),
 ('Paul', 'Jessica'),
 ('Paul', 'Jessica'),
 ('Paul', 'Jessica'),
 ('Paul', 'Jessica'),
 ('Paul', 'Jessica'),
 ('Paul', 'Alia'),
 ('Paul', 'Jessica'),
 ('Leto I', 'Alia'),
 ("Farad'n", "Tuek's Sietch"),
 ('Gurney', 'Paul'),
 ("Farad'n", 'Alia'),
 ('Scytale', 'Edric'),
 ('Jessica', 'Irulan'),
 ('Korba', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Otheym', 'Paul'),
 ('Helen Mohaim', 'Paul'),
 ('Jessica', 'Tharthar'),
 ('Jessica', 'Stilgar'),
 ('Tharthar', 'Stilgar'),
 ('Harah', 'Paul'),
 ('Paul', 'Jessica'),
 ('Duncan', 'Jessica'),
 ('Duncan', 'Leto I'),
 ('Jessica', 'Leto I'),
 ('Jessica', 'Chani'),
 ('Scytale', 'Irulan'),
 ('Chani', 'Tandis'),
 ('Leto I', 'Ghani'),
 ('Chani', 'Paul'),
 ('Liet-Kynes', 'Jessica'),
 ('Hawat', 'Liet-Kynes'),
 ('Tandis', 'Lichna'),
 ('Duncan', 'Scytale'),
 ('Javid', 'Jessica'),
 ('Hawat', 'Bijaz'),
 ('Paul', 'Irulan'),
 ('Ghani', "Farad'n"),
 ('Ghani', 'Jessica'),
 ("Farad'n", 'Jessica'),
 ('Gurney', 'Namri'),
 ('Paul', 'Korba'),
 ('Paul', 'Stilgar'),
 ('Korba', 'Stilgar'),
 ('Stilgar', 'Paul'),
 ('Jessica', 'Paul'),
 ('Duncan', 'Alia'),
 ('Duncan', 'Paul'),
 ('Stilgar', 'Chani'),
 ('Stilgar', 'Gurney'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Leto I'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Leto I'),
 ('Paul', 'Leto I'),
 ('Stilgar', 'Duncan'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Ghani'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Jamis'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Jessica'),
 ('Stilgar', 'Alia'),
 ('Stilgar', 'Gurney'),
 ('Stilgar', 'Alia'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Gurney'),
 ('Stilgar', 'Jamis'),
 ('Chani', 'Paul'),
 ('Jessica', 'Piter'),
 ('Stilgar', 'Chani'),
 ('Paul', 'Gurney'),
 ('Chani', 'Jessica'),
 ('Gurney', 'Paul'),
 ('Stilgar', 'Paul'),
 ('Stilgar', 'Gurney'),
 ('Stilgar', 'Leto I'),
 ('Gurney', 'Leto I'),
 ('Stilgar', 'Paul'),
 ('Ghani', 'Irulan'),
 ('Alia', 'Irulan'),
 ('Stilgar', 'Jessica'),
 ('Paul', 'Alia'),
 ('Paul', 'Stilgar'),
 ('Stilgar', 'Paul'),
 ('Jessica', 'Stilgar'),
 ('Jessica', 'Chani'),
 ('Jessica', 'Liet-Kynes'),
 ('Stilgar', 'Chani'),
 ('Stilgar', 'Liet-Kynes'),
 ('Chani', 'Liet-Kynes'),
 ('Paul', 'Gurney'),
 ('Otheym', 'Paul'),
 ('Leto I', 'Piter'),
 ('Ghani', 'Leto I'),
 ('Helen Mohaim', 'Korba'),
 ('Gurney', 'Jessica'),
 ('Jessica', 'Leto I'),
 ('Javid', 'Jessica'),
 ('Helen Mohaim', 'Farok'),
 ('Gurney', 'Duncan'),
 ('Ghani', 'Jessica'),
 ('Yueh', 'Paul'),
 ('Korba', 'Paul'),
 ('Jamis', 'Stilgar'),
 ('Farok', 'Scytale'),
 ('Stilgar', 'Alia'),
 ('Piter', 'Vladimir'),
 ('Jamis', 'Stilgar'),
 ('Vladimir', 'Irulan'),
 ('Gurney', 'Chani'),
 ('Jamis', 'Harah'),
 ('Paul', 'Alia'),
 ('Jamis', 'Paul'),
 ('Jamis', 'Stilgar'),
 ('Paul', 'Stilgar'),
 ('Vladimir', 'Piter'),
 ('Gurney', 'Paul'),
 ('Jessica', 'Mohandis'),
 ('Jessica', 'Alia'),
 ('Mohandis', 'Alia'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Tharthar'),
 ('Stilgar', 'Tharthar'),
 ('Duncan', 'Jessica'),
 ('Stilgar', 'Ghani'),
 ('Paul', 'Mapes'),
 ('Liet-Kynes', 'Farok'),
 ("Farad'n", 'Ghani'),
 ('Duncan', 'Paul'),
 ('Hawat', 'Paul'),
 ('Hawat', 'Bijaz'),
 ('Liet-Kynes', 'Leto I'),
 ('Leto I', 'Ghani'),
 ('Alia', 'Irulan'),
 ('Alia', 'Duncan'),
 ('Jamis', 'Chani'),
 ('Leto I', 'Liet-Kynes'),
 ("Tuek's Sietch", "Farad'n"),
 ("Tuek's Sietch", "Farad'n"),
 ('Liet-Kynes', 'Paul'),
 ('Alia', "Farad'n"),
 ('Chani', 'Paul'),
 ('Alia', 'Jessica'),
 ('Vladimir', 'Jessica'),
 ('Edric', 'Stilgar'),
 ('Paul', 'Farok'),
 ('Hawat', 'Jessica'),
 ('Hawat', 'Paul'),
 ('Hawat', 'Paul'),
 ('Hawat', 'Paul'),
 ('Hawat', 'Leto I'),
 ('Hawat', 'Paul'),
 ('Paul', 'Chani'),
 ('Jessica', 'Chani'),
 ('Paul', 'Chani'),
 ("Farad'n", 'Mohandis'),
 ('Paul', 'Liet-Kynes'),
 ('Paul', 'Naib'),
 ("Tuek's Sietch", 'Jessica'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Jamis'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Chani'),
 ('Paul', 'Korba'),
 ('Buer Agarves', 'Stilgar'),
 ('Paul', 'Helen Mohaim'),
 ('Jamis', 'Stilgar'),
 ('Liet-Kynes', 'Leto I'),
 ('Korba', 'Paul'),
 ('Liet-Kynes', 'Alia'),
 ('Alia', 'Ghadhean'),
 ('Leto I', 'Hawat'),
 ('Gurney', "Tuek's Sietch"),
 ('Stilgar', 'Ghani'),
 ('Leto I', 'Jessica'),
 ('Paul', 'Gurney'),
 ('Paul', 'Liet-Kynes'),
 ('Gurney', 'Liet-Kynes'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Ghani'),
 ('Scytale', 'Edric'),
 ('Irulan', 'Paul'),
 ('Paul', 'Chani'),
 ('Aramsham', 'Paul'),
 ('Feyd-Rautha', 'Hawat'),
 ('Gurney', 'Paul'),
 ('Paul', 'Irulan'),
 ('Duncan', 'Jessica'),
 ('Glossu', 'Hawat'),
 ('Stilgar', 'Irulan'),
 ('Alia', 'Jessica'),
 ('Alia', 'Jessica'),
 ('Duncan', 'Gurney'),
 ('Paul', 'Piter'),
 ('Bijaz', 'Paul'),
 ('Chani', 'Paul'),
 ('Gurney', 'Paul'),
 ('Paul', 'Leto I'),
 ('Glossu', 'Paul'),
 ('Chani', 'Paul'),
 ('Muriz', 'Leto I'),
 ('Liet-Kynes', 'Jessica'),
 ('Chani', 'Paul'),
 ('Chani', 'Paul'),
 ('Paul', 'Alia'),
 ('Stilgar', 'Alia'),
 ('Liet-Kynes', 'Paul'),
 ('Stilgar', 'Harah'),
 ('Duncan', 'Paul'),
 ('Gurney', 'Leto I'),
 ('Namri', 'Leto I'),
 ('Hawat', 'Jessica'),
 ('Alia', 'Jessica'),
 ('Alia', 'Vladimir'),
 ('Farok', 'Paul'),
 ('Alia', 'Ghani'),
 ('Stilgar', 'Paul'),
 ('Paul', 'Gurney'),
 ('Chani', 'Paul'),
 ('Irulan', 'Ghani'),
 ('Alia', 'Irulan'),
 ('Wensicia', "Tuek's Sietch"),
 ('Wensicia', 'Jessica'),
 ('Wensicia', "Farad'n"),
 ('Jessica', "Farad'n"),
 ('Paul', 'Liet-Kynes'),
 ('Irulan', 'Chani'),
 ('Alia', 'Leto I'),
 ('Stilgar', 'Paul'),
 ('Ziamad', "Farad'n"),
 ('Alia', 'Paul'),
 ('Gurney', 'Paul'),
 ('Paul', 'Stilgar'),
 ('Jessica', 'Mapes'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Stilgar'),
 ('Ghani', 'Alia'),
 ('Ghani', 'Irulan'),
 ('Alia', 'Irulan'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Korba'),
 ('Scytale', 'Irulan'),
 ('Gurney', 'Leto I'),
 ('Namri', 'Gurney'),
 ('Gurney', 'Paul'),
 ('Jessica', 'Wensicia'),
 ('Jessica', "Farad'n"),
 ('Wensicia', "Farad'n"),
 ('Bijaz', 'Dhuri'),
 ('Paul', 'Harah'),
 ('Paul', 'Jessica'),
 ('Jamis', 'Stilgar'),
 ('Stilgar', 'Jamis'),
 ('Gurney', 'Leto I'),
 ('Ghani', "Farad'n"),
 ('Vladimir', 'Piter'),
 ('Stilgar', 'Leto I'),
 ('Lichna', 'Dhuri'),
 ('Irulan', 'Alia'),
 ('Duncan', 'Jessica'),
 ('Alia', 'Wensicia'),
 ('Alia', 'Ghani'),
 ('Glossu', 'Bijaz'),
 ('Paul', 'Jessica'),
 ('Hawat', 'Jessica'),
 ('Hawat', 'Liet-Kynes'),
 ('Paul', 'Bijaz'),
 ('Bannerjee', 'Paul'),
 ('Irulan', 'Ghani'),
 ('Ghani', 'Stilgar'),
 ('Irulan', 'Alia'),
 ('Alia', 'Jessica'),
 ('Duncan', 'Paul'),
 ('Vladimir', 'Paul'),
 ('Hawat', 'Liet-Kynes'),
 ('Hawat', 'Feyd-Rautha'),
 ('Yueh', 'Gurney'),
 ('Irulan', 'Yueh'),
 ('Irulan', 'Paul'),
 ('Yueh', 'Paul'),
 ('Hasimir', 'Elrood IX'),
 ('Irulan', 'Vladimir'),
 ('Edric', 'Paul'),
 ('Paul', 'Leto I'),
 ('Jamis', 'Irulan'),
 ('Jamis', 'Leto I'),
 ('Irulan', 'Leto I'),
 ('Leto II', "Farad'n"),
 ('Leto I', "Farad'n"),
 ('Leto I', 'Alia'),
 ("Farad'n", 'Alia'),
 ('Liet-Kynes', 'Jessica'),
 ('Irulan', 'Jessica'),
 ('Irulan', 'Paul'),
 ('Jessica', 'Paul'),
 ('Lu', 'Leto I'),
 ('Stilgar', 'Irulan'),
 ('Tagir Mohandis', 'Leto I'),
 ("Farad'n", "Tuek's Sietch"),
 ('Paul', 'Alia'),
 ('Leto I', 'Ghani'),
 ("Farad'n", 'Gurney'),
 ("Farad'n", 'Buer Agarves'),
 ('Paul', "Farad'n"),
 ("Farad'n", 'Leto I'),
 ('Irulan', 'Jessica'),
 ('Irulan', 'Hawat'),
 ('Irulan', 'Paul'),
 ('Irulan', 'Paul'),
 ('Irulan', 'Hawat'),
 ('Irulan', 'Stilgar'),
 ('Irulan', 'Yueh'),
 ('Irulan', 'Mapes'),
 ('Yueh', 'Mapes'),
 ('E. Shaddam', 'Leto I'),
 ('Irulan', 'Paul'),
 ('Leto I', 'Irulan'),
 ('Leto I', 'Vladimir'),
 ('Irulan', 'Vladimir'),
 ('Yanshuph Ashkoko', 'Shakkad'),
 ('Yanshuph Ashkoko', 'Paul'),
 ('Shakkad', 'Paul'),
 ('Ghani', "Farad'n"),
 ('Mapes', 'Jessica'),
 ('Javid', 'Alia'),
 ('Jessica', 'Ghadhean'),
 ('Gurney', 'Paul'),
 ('Leto I', 'Hawat'),
 ('Paul', 'Rasir'),
 ('Ghani', 'Alia'),
 ('Paul', 'Edric'),
 ('Gurney', 'Leto I'),
 ('Gurney', 'Namri'),
 ('Leto I', 'Namri'),
 ('Jessica', 'Chani'),
 ('Alia', 'Jessica'),
 ('Alia', 'Vladimir'),
 ('Paul', 'Gurney'),
 ('Paul', 'Leto I'),
 ('Gurney', 'Leto I'),
 ('Leto I', 'Ghani'),
 ('Gurney', 'Javid'),
 ('Jessica', 'Paul'),
 ('Jessica', 'Leto I'),
 ('Jessica', 'Ghani'),
 ('Leto I', 'Ghani'),
 ('Abulurd', 'Vladimir'),
 ('Chani', 'Paul'),
 ('Paul', 'Jessica'),
 ('Jessica', "Farad'n"),
 ('Duncan', 'Jessica'),
 ('Gurney', 'Sabiha'),
 ('Gurney', 'Jessica'),
 ('Leto I', 'Assan'),
 ('Leto I', 'Muriz'),
 ('Stilgar', 'Leto I'),
 ('Chani', 'Jessica'),
 ('Edric', 'Stilgar'),
 ('Gurney', 'Paul'),
 ('Jamis', 'Paul'),
 ('Jessica', 'Harah'),
 ('Mapes', 'Jessica'),
 ('Paul', 'Stilgar'),
 ('Tandis', 'Paul'),
 ('Liet-Kynes', 'Leto I'),
 ('Buer Agarves', 'Javid'),
 ('Buer Agarves', 'Stilgar'),
 ('Buer Agarves', 'Harah'),
 ('Buer Agarves', 'Rajia'),
 ('Stilgar', 'Harah'),
 ('Stilgar', 'Rajia'),
 ('Harah', 'Rajia'),
 ('Leto I', 'Paul'),
 ('Alia', 'Paul'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Duncan'),
 ('Paul', 'Stilgar'),
 ('Paul', 'Duncan'),
 ('Stilgar', 'Duncan'),
 ('Ghadhean al-Fali', 'Stilgar'),
 ('Ghadhean al-Fali', 'Jessica'),
 ('Ghadhean al-Fali', 'Jessica'),
 ('Ghadhean al-Fali', 'Alia'),
 ('Ghadhean al-Fali', 'Jessica'),
 ('Ghadhean al-Fali', 'Jessica'),
 ('Ghadhean al-Fali', 'Jessica'),
 ('Alia', "Farad'n"),
 ('Alia', 'Ghani'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Essas Paymon'),
 ('Alia', 'Vladimir'),
 ('Alia', 'Jessica'),
 ('Alia', 'Tharthar'),
 ('Alia', 'Ghani'),
 ('Alia', 'Jessica'),
 ('Alia', "Farad'n"),
 ('Jessica', "Farad'n"),
 ('Alia', 'Stilgar'),
 ('Alia', 'Vladimir'),
 ('Alia', 'Duncan'),
 ('Alia', 'Leto I'),
 ('Alia', 'Irulan'),
 ('Alia', 'Ziamad'),
 ('Alia', 'Ghani'),
 ('Alia', 'Paul'),
 ('Alia', 'Buer'),
 ('Alia', 'Ziamad'),
 ('Buer', 'Ziamad'),
 ('Alia', 'Paul'),
 ('Alia', 'Chani'),
 ('Paul', 'Chani'),
 ('Alia', 'Harah'),
 ('Alia', 'Ziarenka Valefor'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Jessica'),
 ('Alia', 'Leto I'),
 ('Alia', 'Irulan'),
 ('Alia', 'Irulan'),
 ('Alia', 'Paul'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Paul'),
 ('Alia', 'Ghani'),
 ('Alia', 'Paul'),
 ('Alia', 'Jessica'),
 ('Alia', 'Jessica'),
 ('Alia', 'Jessica'),
 ('Alia', "Farad'n"),
 ('Alia', 'Namri'),
 ('Alia', 'Stilgar'),
 ('Alia', 'Essas Paymon'),
 ('Alia', 'Leto I'),
 ('Hasimir', 'E. Shaddam'),
 ('Alia', 'Stilgar'),
 ('Jessica', 'Leto I'),
 ('Stilgar', 'Paul'),
 ('Feyd-Rautha', 'Hawat'),
 ('Gurney', 'Paul'),
 ('Gurney', 'Paul'),
 ('Paul', 'Paul'),
 ('Hawat', 'Paul'),
 ('Irulan', 'Ghani'),
 ('Jessica', 'Gurney'),
 ('Jessica', 'Jamis'),
 ('Jessica', 'Stilgar'),
 ('Jessica', 'Jamis'),
 ('Jessica', 'Paul'),
 ('Stilgar', 'Jamis'),
 ('Stilgar', 'Paul'),
 ('Jamis', 'Paul'),
 ('Jessica', 'Piter'),
 ('Jessica', 'Duncan'),
 ('Jessica', 'Paul'),
 ('Jessica', 'Paul'),
 ('Jessica', 'Alia'),
 ('Jessica', 'Paul'),
 ('Jessica', 'Gurney'),
 ('Jessica', 'Alia'),
 ('Liet-Kynes', 'Jessica'),
 ('Liet-Kynes', 'Paul'),
 ('Jessica', 'Paul'),
 ('Liet-Kynes', 'Leto I'),
 ('Leto I', "Farad'n"),
 ('Leto I', 'Gurney'),
 ('Paul', 'Gurney'),
 ('Paul', 'Jamis'),
 ('Paul', 'Kaleff'),
 ('Paul', 'Geoff'),
 ('Kaleff', 'Geoff'),
 ('Paul', 'Chani'),
 ('Paul', 'Stilgar'),
 ('Chani', 'Stilgar'),
 ('Paul', 'Gurney'),
 ('Paul', 'Chani'),
 ('Paul', 'Gurney'),
 ('Stilgar', 'Jamis'),
 ("Tuek's Sietch", 'Jessica'),
 ("Tuek's Sietch", 'Wensicia'),
 ('Ziamad', 'Javid'),
 ('Paul', 'Leto I'),
 ('Leto I', 'Ghani'),
 ('Chani', 'Jessica'),
 ('Jessica', 'Paul'),
 ('Hawat', 'Lingar Bewt'),
 ('Hasimir', 'Vladimir'),
 ('Hasimir', 'Feyd-Rautha'),
 ('Vladimir', 'Feyd-Rautha'),
 ('Leto I', 'Alia'),
 ('Hawat', 'Lingar Bewt'),
 ('Paul', 'Vladimir'),
 ('Alia', 'Chani'),
 ('Alia', 'Paul'),
 ('Chani', 'Paul'),
 ('Jessica', 'Paul'),
 ('Jessica', 'Duncan'),
 ('Jessica', 'Gurney'),
 ('Paul', 'Duncan'),
 ('Paul', 'Gurney'),
 ('Duncan', 'Gurney'),
 ('Buer', 'Stilgar'),
 ('Paul', 'Chani'),
 ('Jessica', 'Alia'),
 ('Jessica', 'Ghani'),
 ('Alia', 'Ghani'),

In [ ]:
# Create the DataFrame
edges_df = pd.DataFrame(edges, columns=['source', 'target'])

# Display the first few rows
print(edges_df.head())

     source         target
0    Gurney         Leto I
1  Wensicia  Tuek's Sietch
2     Harah           Alia
3     Edric        Scytale
4     Hawat          Piter

In [ ]:
nodes_df.to_csv("nodes_df_dune.csv", index=False)
edges_df.to_csv("edges_df_dune.csv", index=False)

In [ ]:
# Ensure edges are undirected and count occurrences
edges_df['sorted_edge'] = edges_df.apply(lambda x: tuple(sorted([x['source'], x['target']])), axis=1)
weighted_edges = edges_df.groupby('sorted_edge').size().reset_index(name='Weight')
weighted_edges[['source', 'target']] = pd.DataFrame(weighted_edges['sorted_edge'].tolist(), index=weighted_edges.index)
weighted_edges = weighted_edges[['source', 'target', 'Weight']]

# Filter nodes to include only those in the edges
valid_nodes = set(weighted_edges['source']).union(set(weighted_edges['target']))
filtered_nodes_df = nodes_df[nodes_df['Person'].isin(valid_nodes)]

# Ensure edges only contain nodes in the filtered nodes list
filtered_edges_df = weighted_edges[
    weighted_edges['source'].isin(filtered_nodes_df['Person']) &
    weighted_edges['target'].isin(filtered_nodes_df['Person'])
]

In [ ]:
valid_nodes

{'Abulurd',
 'Abumojandis',
 'Alia',
 'Aramsham',
 'Arkie',
 'Assan',
 'Bannerjee',
 'Behaleth',
 'Bijaz',
 'Bikouros',
 'Buer',
 'Buer Agarves',
 'Cahueit',
 'Chalice',
 'Chani',
 'Chatt',
 'Czigo',
 'Dalak Fenring',
 'Dhuri',
 'Djedida',
 'Duncan',
 'E. Shaddam',
 'Edric',
 'Elrood IX',
 'Esmar',
 'Essas Paymon',
 "Farad'n",
 'Farok',
 'Farrukh',
 'Feyd-Rautha',
 'Geoff',
 'Ghadhean',
 'Ghadhean al-Fali',
 'Ghani',
 'Ghanima',
 'Glossu',
 'Gurney',
 'Harah',
 'Hasimir',
 'Hawat',
 'Helen Mohaim',
 'Hobars',
 'Irulan',
 'Jamis',
 'Javid',
 'Jessica',
 'Josifa',
 'Kaleff',
 'Kinet',
 'Korba',
 'Larus',
 'Legg',
 'Leto I',
 'Leto II',
 'Lichna',
 'Liet-Kynes',
 'Lingar Bewt',
 'Lu',
 'Mapes',
 'Margot Fenring',
 'Melides',
 'Mirzabah',
 'Mitha',
 'Mohandis',
 'Muriz',
 'Naib',
 'Namri',
 'Nefud',
 'Nisai',
 'Ohashi',
 'Orlop',
 'Otheym',
 'Palimbasha',
 'Paul',
 'Piter',
 'Rajia',
 'Ramallo',
 'Rasir',
 'Rugi',
 'Saajid',
 'Sabiha',
 'Scytale',
 'Shakkad',
 'Sheba',
 'Shishakli',
 'Soo-Soo',
 'Staban',
 'Stilgar',
 'Subiay',
 'Tagir Mohandis',
 'Tandis',
 'Tasmin',
 'Tecrube',
 'Tharthar',
 "Tuek's Sietch",
 'Umman',
 'Vladimir',
 'Wanna',
 'Wensicia',
 'Yanshuph Ashkoko',
 'Yueh',
 'Zebataleph',
 'Ziamad',
 'Ziarenka Valefor',
 'Ziarenko Javid',
 'the Bashar Tyekanik'}

In [ ]:
filtered_edges_df

            source         target  Weight
0          Abulurd    Feyd-Rautha       1
1          Abulurd         Glossu       1
2          Abulurd       Vladimir       3
3      Abumojandis      Bannerjee       1
4             Alia           Buer       1
..             ...            ...     ...
388        Stilgar  Tuek's Sietch       3
389        Stilgar         Ziamad       1
390  Tuek's Sietch       Wensicia       6
391       Vladimir          Wanna       1
392          Wanna           Yueh       1

[393 rows x 3 columns]

In [ ]:
from itertools import combinations
import pandas as pd

# Initialize nodes dictionary and edges list
nodes = {}
edges = []

# Group by sentence to identify interactions in the same sentence
grouped = final_df.groupby("sentence")[["Person", "House"]].apply(lambda x: x.values.tolist())

# Populate nodes and edges
for sentence, entities in grouped.items():
    # Add nodes with house information
    for person, house in entities:
        nodes[person] = house

    # Create edges for all pairs of entities in the same sentence
    persons_in_sentence = [person for person, _ in entities]
    edges.extend(combinations(persons_in_sentence, 2))

# Convert nodes into a DataFrame
nodes_df = pd.DataFrame(nodes.items(), columns=["Id", "House"])

# Prepare edges as a DataFrame, including a weight for the number of interactions
edges_df = pd.DataFrame(edges, columns=["source", "target"])
edges_df = edges_df.groupby(["source", "target"]).size().reset_index(name="Weight")

# Ensure only edges where both nodes exist in the nodes_df
valid_edges = edges_df[
    (edges_df["source"].isin(nodes_df["Id"])) &
    (edges_df["target"].isin(nodes_df["Id"]))
]

# Display the resulting DataFrames
print("Nodes DataFrame:")
print(nodes_df.head())

print("\nEdges DataFrame:")
print(valid_edges.head())

Nodes DataFrame:
              Id                 House
0         Gurney              Atreides
1         Leto I              Atreides
2       Wensicia               Corrino
3  Tuek's Sietch  Arrakis Water seller
4          Harah                Fremen

Edges DataFrame:
        source        target  Weight
0      Abulurd      Vladimir       1
1  Abumojandis     Bannerjee       1
2         Alia          Buer       1
3         Alia  Buer Agarves       1
4         Alia         Chani       3

In [ ]:
nodes_df.to_csv("dunes_nodes_df.csv", index=False)
valid_edges.to_csv("dunes_edges_df.csv", index=False)